/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administracionFacturas;
import conexion.conex;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author desarrollo8
 */
public class FacturasGeneradas extends javax.swing.JFrame {
private static TableRowSorter<TableModel> sorter;
    /**
     * Creates new form FacturasGeneradas
     */
    public FacturasGeneradas() {
        initComponents();
         String rutaicon="/images/icono.png";        
        String ruta=rutaicon;      
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
         Calendar c2 = new GregorianCalendar();
        txtfechaini.setCalendar(c2);
        txtfechafin.setCalendar(c2);
        txtfechaini1.setCalendar(c2);
        txtfechafin1.setCalendar(c2);
         cargartabla();
         cargartablacanceladas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtfechaini = new com.toedter.calendar.JDateChooser();
        txtfechafin = new com.toedter.calendar.JDateChooser();
        txtBusqueda = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfacturas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtfechaini1 = new com.toedter.calendar.JDateChooser();
        txtfechafin1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtcanceladas = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de Facturas");

        jPanel2.setBackground(new java.awt.Color(245, 243, 243));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administración de Facturas Electronicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        txtBusqueda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        jButton3.setVisible(true);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setVisible(true);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdfIco.jpg"))); // NOI18N
        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historico.png"))); // NOI18N
        jButton1.setText("XML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfacturas.setDefaultRenderer (Object.class, new MiRender());
        jtfacturas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfacturas.getTableHeader().setReorderingAllowed(false);
        jtfacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Factura", "Cliente", "Subtotal", "Iva", "Total", "Forma Pago", "Folio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtfacturas.setGridColor(new java.awt.Color(255, 255, 255));
        jtfacturas.setRowHeight(24);
        jtfacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtfacturas);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfechaini, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtfechafin, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Facturas Activas", jPanel3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jtcanceladas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtcanceladas.getTableHeader().setReorderingAllowed(false);
        jtcanceladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Genero", "Factura", "Cliente", "Total", "Fecha Cancelacion", "Usuario Cancelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcanceladas.setRowHeight(24);
        jScrollPane2.setViewportView(jtcanceladas);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historico.png"))); // NOI18N
        jButton6.setText("XML");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtfechaini1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfechafin1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfechaini1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfechafin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Facturas Canceladas", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
        txtBusqueda.getDocument().addDocumentListener(new DocumentListener(){
          @Override
          public void insertUpdate(DocumentEvent e) {
              filtrar();
          }
          @Override
          public void removeUpdate(DocumentEvent e) {
              filtrar();
          }
          @Override
          public void changedUpdate(DocumentEvent e) {
              filtrar();
          }
        });
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
        fila=jtfacturas.getSelectedRow();
        if(fila!=-1){
            String id=jtfacturas.getValueAt(jtfacturas.getSelectedRow(),1).toString();  
            File fichero = new File("");
            String rutaarchivo=fichero.getAbsolutePath()+"\\facturacion\\facturas_xml\\"+id+".xml";
            System.out.println(rutaarchivo);
            javax.swing.JFileChooser jF1= new javax.swing.JFileChooser(); 
            String ruta = ""; 
            if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
                ruta = jF1.getSelectedFile().getAbsolutePath()+".xml"; 
                System.out.println("ruta: "+ruta);
                String destino=ruta;
                try {
                        InputStream in = new FileInputStream(rutaarchivo);
                        OutputStream out = new FileOutputStream(destino);                                
                        byte[] buf = new byte[1024];
                        int len;
                        while ((len = in.read(buf)) > 0) {
                                out.write(buf, 0, len);
                        }                
                        in.close();
                        out.close();
                        JOptionPane.showMessageDialog(null, "El archivo se guardo correctamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ioe){
                        JOptionPane.showMessageDialog(null, "Error al copiar el archivo. "+ioe.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        //ioe.printStackTrace();
                }
            }else{
            
            }
            
                
            
            
            /*try {
                Runtime.getRuntime().exec("cmd /c start "+rutaarchivo);
            } catch (IOException ex) {
                Logger.getLogger(FacturasGeneradas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }else{
            JOptionPane.showMessageDialog(null,"Favor de seleccionar una factura.","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
            fila=jtfacturas.getSelectedRow();
            if(fila!=-1){
                String factura=jtfacturas.getValueAt(jtfacturas.getSelectedRow(),1).toString();      
                int response = JOptionPane.showConfirmDialog(null, "Desea cancelar la factura "+factura+"?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    System.out.println("Yes button clicked");                                    
                    System.out.println(""+factura);
                    
                    //CANCELACION SMARTWEB
                    CancelarFacturaSmartWeb cancela=new CancelarFacturaSmartWeb();
                    boolean validacancelacion=cancela.cancelafactura(factura);
                    
                    //CANCELACION INVOICE ONE
                    //CancelarFactura cancela=new CancelarFactura();
                    //boolean validacancelacion=cancela.cancelafactura(factura);
                    if(validacancelacion){
                        cargartabla();
                        JOptionPane.showMessageDialog(null, "La factura se cancelo correctemente", "Factura Cancelada", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "No se pudo cancelar la factura.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }    
            }else{
                JOptionPane.showMessageDialog(null,"Favor de seleccionar una factura.","Alerta",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         cargartabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cargartablacanceladas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
        fila=jtcanceladas.getSelectedRow();
        if(fila!=-1){
            String id=jtcanceladas.getValueAt(jtcanceladas.getSelectedRow(),1).toString();  
            File fichero = new File("");
            String rutaarchivo=fichero.getAbsolutePath()+"\\facturacion\\facturas_xml\\"+id+"_cancelada.xml";
            System.out.println(rutaarchivo);
            javax.swing.JFileChooser jF1= new javax.swing.JFileChooser(); 
            String ruta = ""; 
            if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
                ruta = jF1.getSelectedFile().getAbsolutePath()+".xml"; 
                System.out.println("ruta: "+ruta);
                String destino=ruta;
                try {
                        InputStream in = new FileInputStream(rutaarchivo);
                        OutputStream out = new FileOutputStream(destino);                                
                        byte[] buf = new byte[1024];
                        int len;
                        while ((len = in.read(buf)) > 0) {
                                out.write(buf, 0, len);
                        }                
                        in.close();
                        out.close();
                        JOptionPane.showMessageDialog(null, "El archivo se guardo correctamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ioe){
                        JOptionPane.showMessageDialog(null, "Error al copiar el archivo. "+ioe.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        //ioe.printStackTrace();
                }
            }else{
            
            }
            
                
            
            
            /*try {
                Runtime.getRuntime().exec("cmd /c start "+rutaarchivo);
            } catch (IOException ex) {
                Logger.getLogger(FacturasGeneradas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }else{
            JOptionPane.showMessageDialog(null,"Favor de seleccionar una factura.","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int fila=-1;
        fila=jtfacturas.getSelectedRow();
        if(fila!=-1){
            String id=jtfacturas.getValueAt(jtfacturas.getSelectedRow(),1).toString();  
            File fichero = new File("");
            String rutaarchivo=fichero.getAbsolutePath()+"\\facturacion\\facturas_xml\\"+id+".pdf";
            System.out.println(rutaarchivo);
            javax.swing.JFileChooser jF1= new javax.swing.JFileChooser(); 
            String ruta = ""; 
            if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
                ruta = jF1.getSelectedFile().getAbsolutePath()+".pdf"; 
                System.out.println("ruta: "+ruta);
                String destino=ruta;
                try {
                        InputStream in = new FileInputStream(rutaarchivo);
                        OutputStream out = new FileOutputStream(destino);                                
                        byte[] buf = new byte[1024];
                        int len;
                        while ((len = in.read(buf)) > 0) {
                                out.write(buf, 0, len);
                        }                
                        in.close();
                        out.close();
                        JOptionPane.showMessageDialog(null, "El archivo se guardo correctamente.", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ioe){
                    JOptionPane.showMessageDialog(null, "Error al copiar el archivo. "+ioe.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    System.out.println("errror: ");
                        //ioe.printStackTrace();
                }
            }else{
            
            }
            
                
            
            
            /*try {
                Runtime.getRuntime().exec("cmd /c start "+rutaarchivo);
            } catch (IOException ex) {
                Logger.getLogger(FacturasGeneradas.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }else{
            JOptionPane.showMessageDialog(null,"Favor de seleccionar una factura.","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasGeneradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasGeneradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasGeneradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasGeneradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturasGeneradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtcanceladas;
    private javax.swing.JTable jtfacturas;
    private javax.swing.JTextField txtBusqueda;
    private com.toedter.calendar.JDateChooser txtfechafin;
    private com.toedter.calendar.JDateChooser txtfechafin1;
    private com.toedter.calendar.JDateChooser txtfechaini;
    private com.toedter.calendar.JDateChooser txtfechaini1;
    // End of variables declaration//GEN-END:variables

    public void vaciartabla(){
            DefaultTableModel modelo=(DefaultTableModel) jtfacturas.getModel();         
            for (int i = 0; i < jtfacturas.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
   public void cargartabla(){    
        vaciartabla();
        
        Date fecha=txtfechaini.getDate();
        Date fecha2=txtfechafin.getDate();
        SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
        String fechaini=fechaformateada.format(fecha);
        String fechafin=fechaformateada.format(fecha2);
        String sqlaux=" and FechaGeneracion>='"+fechaini+" 00:00' and FechaGeneracion<='"+fechafin+" 23:59'";
        
        DefaultTableModel modelo=(DefaultTableModel) jtfacturas.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select FechaGeneracion,factura,razon_social,subtotal,iva,Monto,to_facturas.MetodoPago,folio from to_facturas,tc_clientes where idr_cliente=idcliente and uuid is not null and factura is not null and to_facturas.estatus is null"+sqlaux+" order by factura desc;";
               System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("FechaGeneracion"),rsR.getString("factura"),rsR.getString("razon_social"),"$"+rsR.getString("subtotal"),"$"+rsR.getString("iva"),"$"+rsR.getString("Monto"),rsR.getString("MetodoPago"),rsR.getString("folio")});                        
                   }
                   sorter = new TableRowSorter<TableModel>(modelo);
                   jtfacturas.setRowSorter(sorter);
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    } 
    private void filtrar() {
        
         RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("(?i)"+txtBusqueda.getText(),1,2);
        }catch (java.util.regex.PatternSyntaxException e) {
        }
        sorter.setRowFilter(rf);
    }  
    
    
    
    public void vaciartablacanceladas(){
            DefaultTableModel modelo=(DefaultTableModel) jtcanceladas.getModel();         
            for (int i = 0; i < jtcanceladas.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
   public void cargartablacanceladas(){    
        vaciartablacanceladas();
        
        Date fecha=txtfechaini1.getDate();
        Date fecha2=txtfechafin1.getDate();
        SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
        String fechaini=fechaformateada.format(fecha);
        String fechafin=fechaformateada.format(fecha2);
        String sqlaux=" and FechaGeneracion>='"+fechaini+" 00:00' and FechaGeneracion<='"+fechafin+" 23:59'";
        
        DefaultTableModel modelo=(DefaultTableModel) jtcanceladas.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select FechaGeneracion,factura,razon_social,subtotal,iva,Monto,to_facturas.MetodoPago,folio,fecha_cancelacion,usuario_cancelacion from to_facturas,tc_clientes where idr_cliente=idcliente and uuid is not null and factura is not null and to_facturas.estatus =5"+sqlaux+" order by factura desc;";
               //System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("FechaGeneracion"),rsR.getString("factura"),rsR.getString("razon_social"),"$"+rsR.getString("Monto"),rsR.getString("fecha_cancelacion"),rsR.getString("usuario_cancelacion")});                        
                   }
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    } 

   
   
public class MiRender extends DefaultTableCellRenderer
{
   public Component getTableCellRendererComponent(JTable table,
      Object value,
      boolean isSelected,
      boolean hasFocus,
      int row,
      int column)
   {
      Component comp = super.getTableCellRendererComponent (table, value, isSelected, hasFocus, row, column);
      boolean oddRow = (row % 2 == 0);
      Color azul = new Color(220, 248, 239);
      Color blanco = new Color(255,255,255);
      Color seleccion = new Color(75, 131, 141);    
      
      
      if ( oddRow ){
                 
         //if(column==2){
             this.setBackground(azul);
            this.setForeground(Color.BLACK);         
         /*}else{
             this.setBackground(blanco);
             this.setForeground(Color.BLACK); 
         }*/
      } else {
          
          /*if(column==2){
             this.setBackground(azul);
            this.setForeground(Color.white);         
         }else{*/
             this.setBackground(blanco);
             this.setForeground(Color.BLACK); 
         //}
          //this.setBackground(d);
          //this.setForeground(Color.BLACK);  
         // Restaurar los valores por defecto
      }    
      
       if(isSelected){
            this.setBackground(seleccion);
            this.setForeground(Color.white);   
      }
      
        
      return this;
   }
}   
   
   
}
