/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloVeterinaria;

import ClasesDAO.accesoSistema;
import Utilerias.funciones;
import conexion.conex;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo8
 */
public class DetallePacientedialog extends javax.swing.JDialog {
String idpaciente="";
    /**
     * Creates new form DetallePacientedialog
     */
    public DetallePacientedialog(java.awt.Frame parent, boolean modal,String id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); 
        idpaciente=id;
        Calendar c2 = new GregorianCalendar();
        txtfechaini.setCalendar(c2);
        
        cargartablaCITAS();
        cargartablacontrolmedico();
        cargartablaparasito();
        cargartablavacunas();
         
        jtcitas.getColumnModel().getColumn(0).setMaxWidth(0);
        jtcitas.getColumnModel().getColumn(0).setMinWidth(0);
        jtcitas.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtcitas.getColumnModel().getColumn(0).setWidth(0);
        
        jtcitas.getColumnModel().getColumn(1).setMaxWidth(95);
        jtcitas.getColumnModel().getColumn(1).setMinWidth(95);
        jtcitas.getColumnModel().getColumn(1).setPreferredWidth(95);
        jtcitas.getColumnModel().getColumn(1).setWidth(95);
        
        jtcitas.getColumnModel().getColumn(3).setMaxWidth(0);
        jtcitas.getColumnModel().getColumn(3).setMinWidth(0);
        jtcitas.getColumnModel().getColumn(3).setPreferredWidth(0);
        jtcitas.getColumnModel().getColumn(3).setWidth(0);
        
        jtcitas.getColumnModel().getColumn(4).setMaxWidth(95);
        jtcitas.getColumnModel().getColumn(4).setMinWidth(95);
        jtcitas.getColumnModel().getColumn(4).setPreferredWidth(95);
        jtcitas.getColumnModel().getColumn(4).setWidth(95);
        
        
        try {
            String consulta="SELECT nombrepaciente,sexo,observaciones,color,fecha_nacimiento, timestampdiff(month,fecha_nacimiento,curdate()) as edad FROM tc_mascotas where Idmascota="+idpaciente;
            conex con=new conex();
            Statement st = con.getConnection().createStatement();
            ResultSet rs=st.executeQuery(consulta);   
            while (rs.next())
            {                       
                 txtpaciente.setText(rs.getString("nombrepaciente"));
                 txtsexo.setText(rs.getString("sexo"));
                 String edad="";
                 int meses=rs.getInt("edad");
                 int anio=0;
                 int mesesdividido=0;
                 if(meses>=12){ //tiene mas de un año
                     anio=meses/12;
                     mesesdividido=meses-(anio*12);
                     edad=anio+" año(s) "+mesesdividido+" meses";
                 }else{//tiene menos de un año
                     edad=meses+" meses";
                 }
                 txtedad.setText(edad);
                 txtfechanacio.setText(rs.getString("fecha_nacimiento"));
                 txtobservaciones.setText(rs.getString("observaciones"));
                 txtcolor.setText(rs.getString("color"));
                 
            }
            rs.close();
            st.close();
            con.desconectar();    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener la informacion del paciente "+ex, "Error sql", JOptionPane.ERROR_MESSAGE);
        }
        
        
        funciones obtenimagen=new funciones();
        Image foto=obtenimagen.obtenImagenes("SELECT imagen FROM tc_mascotas where Idmascota="+idpaciente);
        if(foto==null){
            jlfoto.setText("");
            jlfoto.setIcon(null);
            jPanel2.updateUI();
        }else{        
            ImageIcon icon = new ImageIcon(foto.getScaledInstance(jlfoto.getWidth(), jlfoto.getHeight(), Image.SCALE_DEFAULT));
            jlfoto.setText("");
            jlfoto.setIcon(icon);
            jPanel2.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jlfoto = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpaciente = new javax.swing.JTextField();
        txtfechanacio = new javax.swing.JTextField();
        txtsexo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtultimavacuna = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobservaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtultimaconsulta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtobservacionesconsulta = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcitas = new javax.swing.JTable();
        txtfechaini = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtobservacion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txttemp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtfr = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtfc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtrt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtrd = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txttllc = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtmucosa = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtpabd = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtgrm = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtgp = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtpulmones = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtvacunas = new javax.swing.JTable();
        txtfechavacunas = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtlote = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtvacunas = new javax.swing.JTextField();
        txtfecharevacunacion = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtparasitos = new javax.swing.JTable();
        txtfechaparacitos = new com.toedter.calendar.JDateChooser();
        txtproducto = new javax.swing.JTextField();
        txtlaboratorio = new javax.swing.JTextField();
        txtcita = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtcontrolmedico = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtcontrol = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expediente del Paciente");

        jPanel2.setBackground(new java.awt.Color(249, 248, 248));

        jlfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 1, true));

        jTabbedPane1.setBackground(new java.awt.Color(252, 252, 252));

        jPanel1.setBackground(new java.awt.Color(249, 248, 248));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Paciente:");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha Nacimiento:");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Color:");

        jLabel5.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Observaciones:");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ultima vacuna:");

        txtpaciente.setEditable(false);
        txtpaciente.setBackground(new java.awt.Color(255, 102, 0));
        txtpaciente.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtpaciente.setForeground(new java.awt.Color(255, 255, 255));

        txtfechanacio.setEditable(false);
        txtfechanacio.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txtsexo.setEditable(false);
        txtsexo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txtcolor.setEditable(false);
        txtcolor.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txtultimavacuna.setEditable(false);
        txtultimavacuna.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        txtobservaciones.setEditable(false);
        txtobservaciones.setColumns(20);
        txtobservaciones.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtobservaciones.setRows(5);
        jScrollPane2.setViewportView(txtobservaciones);

        jLabel7.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Edad:");

        txtedad.setEditable(false);
        txtedad.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ultima Consulta:");

        txtultimaconsulta.setEditable(false);
        txtultimaconsulta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Observ. Consulta:");

        txtobservacionesconsulta.setEditable(false);
        txtobservacionesconsulta.setColumns(20);
        txtobservacionesconsulta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtobservacionesconsulta.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechanacio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtultimavacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtultimaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtobservacionesconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpaciente)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechanacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtultimavacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtultimaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtobservacionesconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Generales", jPanel1);

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));

        jLabel11.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Fecha Sig. Consulta:");

        jLabel12.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Observaciones:");

        jtcitas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtcitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha Registro", "Observación", "Usuario Registro", "Proxima Consulta", "Temp.", "FR", "FC", "Peso", "RT", "RD", "TLLC", "Mucosas", "P. Abd", "GRM", "GP", "Pulmones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcitas.setRowHeight(24);
        jScrollPane1.setViewportView(jtcitas);

        txtobservacion.setColumns(20);
        txtobservacion.setRows(5);
        jScrollPane3.setViewportView(txtobservacion);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Temperatura:");

        jLabel23.setText("FR:");

        jLabel24.setText("FC:");

        jLabel25.setText("Peso:");

        jLabel26.setText("RT:");

        jLabel27.setText("RD:");

        jLabel28.setText("TLLC:");

        jLabel29.setText("Mucosas:");

        jLabel30.setText("P. Abd:");

        jLabel31.setText("GRM:");

        jLabel32.setText("GP:");

        jLabel33.setText("Pulmones:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttllc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtpabd)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtgrm)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtrt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtgp)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtpulmones, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtfr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txttllc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtmucosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtpabd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtgrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtpulmones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", jPanel3);

        jPanel4.setBackground(new java.awt.Color(252, 252, 252));

        jtvacunas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtvacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Vacuna", "Lote", "Revacunacion", "Usuario Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtvacunas.setRowHeight(22);
        jScrollPane8.setViewportView(jtvacunas);

        jLabel18.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Fecha :");

        jLabel19.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Lote:");

        txtlote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Vacuna:");

        jLabel21.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("ReVacunación:");

        txtvacunas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtfechavacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtlote, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtvacunas))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfecharevacunacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 78, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfechavacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtvacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtlote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfecharevacunacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vacunas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(252, 252, 252));

        jLabel14.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Fecha :");

        jLabel15.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Producto:");

        jLabel16.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Laboratorio:");

        jLabel17.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Prox. Cita:");

        jtparasitos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtparasitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Producto", "Laboratorio", "Proxima Cita"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtparasitos.setRowHeight(22);
        jScrollPane5.setViewportView(jtparasitos);

        txtproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtlaboratorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechaparacitos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlaboratorio)
                            .addComponent(txtcita, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtlaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcita, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfechaparacitos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Control Parasitos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(252, 252, 252));

        jtcontrolmedico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtcontrolmedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Registro", "Observaciones", "Usuario Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcontrolmedico.setRowHeight(22);
        jScrollPane6.setViewportView(jtcontrolmedico);

        txtcontrol.setColumns(20);
        txtcontrol.setRows(5);
        jScrollPane7.setViewportView(txtcontrol);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 2, 19)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Control Medico:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Control Medico", jPanel6);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Fotografia del Paciente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        String observacion=txtobservacion.getText().trim();
        Date fecha=txtfechaini.getDate();        
        if(fecha==null){
            JOptionPane.showMessageDialog(null, "Falta ingresar la fecha.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(observacion.equals("")){
            JOptionPane.showMessageDialog(null, "falta ingresar la observacion.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else{
            SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
            String fechaformateadas=fechaformateada.format(fecha);
            
            conex con=new conex();  
            try {
                Statement st = con.getConnection().createStatement();
                String myQuery = "insert into veterinaria_consultas (proxima_cita,fecha_consulta,observaciones,fecha_registro,usuario_registro,idrpaciente,temperatura,fr,fc,peso,rt,rd,tllc,mucosas,pabd,grm,gp,pulmones) values('"+fechaformateadas+"',now(),'"+observacion+"',now(),'"+accesoSistema.nombreuser+"','"+idpaciente+"','"+txttemp.getText().trim()+"','"+txtfr.getText().trim()+"','"+txtfc.getText().trim()+"','"+txtpeso.getText().trim()+"','"+txtrt.getText().trim()+"','"+txtrd.getText().trim()+"','"+txttllc.getText().trim()+"','"+txtmucosa.getText().trim()+"','"+txtpabd.getText().trim()+"','"+txtgrm.getText().trim()+"','"+txtgp.getText().trim()+"','"+txtpulmones.getText().trim()+"')";
                st.executeUpdate(myQuery);                                
                st.close();
                con.desconectar();  
                txtobservacion.setText("");   
                txttemp.setText("");   
                txtfr.setText("");   
                txtfc.setText("");   
                txtpeso.setText("");   
                txtrt.setText("");   
                txtrd.setText("");   
                txttllc.setText("");   
                txtmucosa.setText("");   
                txtpabd.setText("");   
                txtgrm.setText("");   
                txtgp.setText("");   
                txtpulmones.setText("");   
                cargartablaCITAS();
                JOptionPane.showMessageDialog(null, "La cita se registro correctamente.", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {       
                JOptionPane.showMessageDialog(null, "Error al registrar la cita: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String controlmedico=txtcontrol.getText().trim();
        if(controlmedico.equals("")){
                JOptionPane.showMessageDialog(null, "Falta ingresar la descripcion del control medico.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else{
            conex con=new conex();  
            try {
                Statement st = con.getConnection().createStatement();
                String myQuery = "insert into veterinaria_to_controlmedico (descripcion,fecharegistro,usuario_registro,idrpaciente) values('"+controlmedico+"',now(),'"+accesoSistema.nombreuser+"','"+idpaciente+"')";
                st.executeUpdate(myQuery);                                
                st.close();
                con.desconectar();  
                txtcontrol.setText("");       
                cargartablacontrolmedico();
                JOptionPane.showMessageDialog(null, "El control medico se registro correctamente.", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {       
                JOptionPane.showMessageDialog(null, "Error al registrar la control medico: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String producto=txtproducto.getText().trim();
        String laboratorio=txtlaboratorio.getText().trim();        
        Date cita=txtcita.getDate();
        Date fecha=txtfechaini.getDate();        
        
        if(fecha==null){
            JOptionPane.showMessageDialog(null, "Falta seleccionar la fecha.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(laboratorio.equals("")){
            JOptionPane.showMessageDialog(null, "falta ingresar el laboratorio.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(producto.equals("")){
            JOptionPane.showMessageDialog(null, "falta ingresar el producto.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(cita==null){
            JOptionPane.showMessageDialog(null, "falta seleccionar la fecha de cita.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else{
            SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
            String fechaformateadas=fechaformateada.format(fecha);
            String fechaformateadascita=fechaformateada.format(cita);
            
            conex con=new conex();  
            try {
                Statement st = con.getConnection().createStatement();
                String myQuery = "insert into veterinaria_parasitos (fechacontrolparacito,producto,laboratorio,cita,fecha_registro,usuario_registro,idrpaciente) values('"+fechaformateadas+"','"+producto+"','"+laboratorio+"','"+fechaformateadascita+"',now(),'"+accesoSistema.nombreuser+"','"+idpaciente+"')";
                st.executeUpdate(myQuery);                                
                st.close();
                con.desconectar();  
                txtproducto.setText("");                
                txtlaboratorio.setText(""); 
                cargartablaparasito();
                JOptionPane.showMessageDialog(null, "El control de parasito se registro correctamente.", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {       
                JOptionPane.showMessageDialog(null, "Error al registrar el control de paracitos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String lote=txtlote.getText().trim();
        String vacuna=txtvacunas.getText().trim();
        Date fecha=txtfechavacunas.getDate();        
        Date fecharevacunacion=txtfecharevacunacion.getDate();        
        if(fecha==null){
            JOptionPane.showMessageDialog(null, "Falta seleccionar la fecha de la vacuna.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(lote.equals("")){
            JOptionPane.showMessageDialog(null, "falta ingresar el lote.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(vacuna.equals("")){
            JOptionPane.showMessageDialog(null, "falta ingresar la vacuna.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else if(fecharevacunacion==null){
            JOptionPane.showMessageDialog(null, "falta seleccionar la fecha de revacunación.", "Validacion campos", JOptionPane.ERROR_MESSAGE);
        }else{
            SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
            String fechaformateadas=fechaformateada.format(fecha);
            String fechaformateadasrevacunacion=fechaformateada.format(fecharevacunacion);
            
            conex con=new conex();  
            try {
                Statement st = con.getConnection().createStatement();
                String myQuery = "insert into veterinaria_to_vacunas (idrpaciente,fecha,lote,vacuna,revacunacion,fecha_registro,usuario_registro) values('"+idpaciente+"','"+fechaformateadas+"','"+lote+"','"+vacuna+"','"+fechaformateadasrevacunacion+"',now(),'"+accesoSistema.nombreuser+"')";
                System.out.println(""+myQuery);
                st.executeUpdate(myQuery);                                
                st.close();
                con.desconectar();  
                txtvacunas.setText("");    
                txtlote.setText("");    
                cargartablavacunas();
                JOptionPane.showMessageDialog(null, "La vacuna se registro correctamente.", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {       
                JOptionPane.showMessageDialog(null, "Error al registrar la vacuna: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallePacientedialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallePacientedialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallePacientedialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallePacientedialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallePacientedialog dialog = new DetallePacientedialog(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jlfoto;
    private javax.swing.JTable jtcitas;
    private javax.swing.JTable jtcontrolmedico;
    private javax.swing.JTable jtparasitos;
    private javax.swing.JTable jtvacunas;
    private com.toedter.calendar.JDateChooser txtcita;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextArea txtcontrol;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtfc;
    private com.toedter.calendar.JDateChooser txtfechaini;
    private javax.swing.JTextField txtfechanacio;
    private com.toedter.calendar.JDateChooser txtfechaparacitos;
    private com.toedter.calendar.JDateChooser txtfecharevacunacion;
    private com.toedter.calendar.JDateChooser txtfechavacunas;
    private javax.swing.JTextField txtfr;
    private javax.swing.JTextField txtgp;
    private javax.swing.JTextField txtgrm;
    private javax.swing.JTextField txtlaboratorio;
    private javax.swing.JTextField txtlote;
    private javax.swing.JTextField txtmucosa;
    private javax.swing.JTextArea txtobservacion;
    private javax.swing.JTextArea txtobservaciones;
    private javax.swing.JTextArea txtobservacionesconsulta;
    private javax.swing.JTextField txtpabd;
    private javax.swing.JTextField txtpaciente;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtpulmones;
    private javax.swing.JTextField txtrd;
    private javax.swing.JTextField txtrt;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txttemp;
    private javax.swing.JTextField txttllc;
    private javax.swing.JTextField txtultimaconsulta;
    private javax.swing.JTextField txtultimavacuna;
    private javax.swing.JTextField txtvacunas;
    // End of variables declaration//GEN-END:variables


    public void vaciartablaCITAS(){
            DefaultTableModel modelo=(DefaultTableModel) jtcitas.getModel();         
            for (int i = 0; i < jtcitas.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
public void cargartablaCITAS(){    
        vaciartablaCITAS();
        DefaultTableModel modelo=(DefaultTableModel) jtcitas.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from veterinaria_consultas where idrpaciente='"+idpaciente+"' order by fecha_consulta desc";
               //System.out.println(""+myQuery);
               int i=0;
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            if(i==0){
                                txtultimaconsulta.setText(rsR.getString("fecha_consulta"));
                                txtobservacionesconsulta.setText(rsR.getString("observaciones"));
                            }
                            i++;
                            modelo.addRow(new Object[]{rsR.getString("Id"),rsR.getString("fecha_consulta"),rsR.getString("observaciones"),rsR.getString("usuario_registro"),rsR.getString("proxima_cita"),rsR.getString("temperatura"),rsR.getString("fr"),rsR.getString("fc"),rsR.getString("peso"),rsR.getString("rt"),rsR.getString("rd"),rsR.getString("tllc"),rsR.getString("mucosas"),rsR.getString("pabd"),rsR.getString("grm"),rsR.getString("gp"),rsR.getString("pulmones")});                        
                   }                                      
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }


public void vaciartablacontrolmedico(){
            DefaultTableModel modelo=(DefaultTableModel) jtcontrolmedico.getModel();         
            for (int i = 0; i < jtcontrolmedico.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
public void cargartablacontrolmedico(){    
        vaciartablacontrolmedico();
        DefaultTableModel modelo=(DefaultTableModel) jtcontrolmedico.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from veterinaria_to_controlmedico where idrpaciente='"+idpaciente+"' order by Idcontrol desc";
               //System.out.println(""+myQuery);               
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                                            
                            modelo.addRow(new Object[]{rsR.getString("fecharegistro"),rsR.getString("descripcion"),rsR.getString("usuario_registro")});                        
                   }                                      
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }



public void vaciartablaparasito(){
            DefaultTableModel modelo=(DefaultTableModel) jtparasitos.getModel();         
            for (int i = 0; i < jtparasitos.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
public void cargartablaparasito(){    
        vaciartablaparasito();
        DefaultTableModel modelo=(DefaultTableModel) jtparasitos.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from veterinaria_parasitos where idrpaciente='"+idpaciente+"' order by IdParasito desc";
               //System.out.println(""+myQuery);               
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                                            
                            modelo.addRow(new Object[]{rsR.getString("fechacontrolparacito"),rsR.getString("producto"),rsR.getString("laboratorio"),rsR.getString("cita"),rsR.getString("usuario_registro")});                        
                   }                                      
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {                         
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }



public void vaciartablavacunas(){
            DefaultTableModel modelo=(DefaultTableModel) jtvacunas.getModel();         
            for (int i = 0; i < jtvacunas.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
public void cargartablavacunas(){    
        vaciartablavacunas();
        DefaultTableModel modelo=(DefaultTableModel) jtvacunas.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from veterinaria_to_vacunas where idrpaciente='"+idpaciente+"' order by Idvacunas desc";
               //System.out.println(""+myQuery);               
               int i=0;
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                                            
                            if(i==0){
                                txtultimavacuna.setText(rsR.getString("fecha")+"  "+rsR.getString("vacuna"));                                
                            }
                            i++;
                            modelo.addRow(new Object[]{rsR.getString("fecha"),rsR.getString("vacuna"),rsR.getString("lote"),rsR.getString("revacunacion"),rsR.getString("usuario_registro")});                        
                   }                                      
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {                         
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }



}
