
package iointegradorcfdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ioIntegradorCFDI", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://invoiceone.mx/timbreCFDI/iointegradorcfdi.asmx?wsdl")
public class IoIntegradorCFDI
    extends Service
{

    private final static URL IOINTEGRADORCFDI_WSDL_LOCATION;
    private final static WebServiceException IOINTEGRADORCFDI_EXCEPTION;
    private final static QName IOINTEGRADORCFDI_QNAME = new QName("http://tempuri.org/", "ioIntegradorCFDI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://invoiceone.mx/timbreCFDI/iointegradorcfdi.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IOINTEGRADORCFDI_WSDL_LOCATION = url;
        IOINTEGRADORCFDI_EXCEPTION = e;
    }

    public IoIntegradorCFDI() {
        super(__getWsdlLocation(), IOINTEGRADORCFDI_QNAME);
    }

    public IoIntegradorCFDI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IoIntegradorCFDISoap
     */
    @WebEndpoint(name = "ioIntegradorCFDISoap")
    public IoIntegradorCFDISoap getIoIntegradorCFDISoap() {
        return super.getPort(new QName("http://tempuri.org/", "ioIntegradorCFDISoap"), IoIntegradorCFDISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IoIntegradorCFDISoap
     */
    @WebEndpoint(name = "ioIntegradorCFDISoap")
    public IoIntegradorCFDISoap getIoIntegradorCFDISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ioIntegradorCFDISoap"), IoIntegradorCFDISoap.class, features);
    }

    /**
     * 
     * @return
     *     returns IoIntegradorCFDISoap
     */
    @WebEndpoint(name = "ioIntegradorCFDISoap12")
    public IoIntegradorCFDISoap getIoIntegradorCFDISoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ioIntegradorCFDISoap12"), IoIntegradorCFDISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IoIntegradorCFDISoap
     */
    @WebEndpoint(name = "ioIntegradorCFDISoap12")
    public IoIntegradorCFDISoap getIoIntegradorCFDISoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ioIntegradorCFDISoap12"), IoIntegradorCFDISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IOINTEGRADORCFDI_EXCEPTION!= null) {
            throw IOINTEGRADORCFDI_EXCEPTION;
        }
        return IOINTEGRADORCFDI_WSDL_LOCATION;
    }

}
