/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jdialog;

import ClasesDAO.accesoSistema;
import administracionFacturas.claveproductosSAT;
import conexion.conex;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jinternalPanel.Productos;

/**
 *
 * @author desarrollo8
 */
public class EdicionProducto extends javax.swing.JDialog {
String id_prod="";
    /**
     * Creates new form EdicionProducto
     */
    public EdicionProducto(java.awt.Frame parent, boolean modal,String id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        id_prod=id;
        cargarcategorias();
        conex con=new conex();  
            try {
                String categorias="";
                String myQuery = "select * from tc_productos where idproducto='"+id_prod+"'";
                System.out.println(""+myQuery);
                ResultSet rsR = null; 
                Statement st = con.getConnection().createStatement();
                rsR = st.executeQuery(myQuery);
                String idconcepto="";
                while(rsR.next()) {                                                
                        txtproducto.setText(rsR.getString("nombre_producto"));
                        txtcodigobarra.setText(rsR.getString("codigo_barras"));
                        txtcompra.setText(rsR.getString("precio_compra"));
                        txtventa.setText(rsR.getString("precio_venta"));
                        txtminimo.setText(rsR.getString("cantidad_minima"));
                        txtmayoreo.setText(rsR.getString("precio_mayoreo"));
                        txtcantmayoreo.setText(rsR.getString("cantidad_mayoreo"));
                        txtcantpromo.setText(rsR.getString("cantidad_promocion"));
                        txtpreciopromo.setText(rsR.getString("precio_promocion"));
                        txtieps.setText(rsR.getString("ieps"));
                        categorias=rsR.getString("idrcategoria");
                        jcagranel.setSelectedItem(rsR.getString("agranel"));
                        jcprodcompuesto.setSelectedItem(rsR.getString("prodcompuesto"));
                        txtcampo1.setText(rsR.getString("campo1"));
                        txtcampo2.setText(rsR.getString("campo2"));
                        txtclavesat.setText(rsR.getString("idr_concep_sat"));
                        idconcepto=rsR.getString("idr_concep_sat");
                        
                }
                if(categorias==null){
                }else{
                    myQuery="select * from tc_categorias where Idcategoria="+categorias;
                    rsR = st.executeQuery(myQuery);
                    String catcompuesto="";
                    if(rsR.next()) {                                                
                           catcompuesto=rsR.getString("Idcategoria")+"-"+rsR.getString("nombre"); 
                           jccategoria.setSelectedItem(catcompuesto);
                    }                    
                }
                if(idconcepto==null){
                }else{
                    myQuery="select * from fact_concepto_productos where IdConceptos="+idconcepto;
                    rsR = st.executeQuery(myQuery);
                    String catcompuesto="";
                    if(rsR.next()) {                                                                           
                           jlconceptosat.setText(rsR.getString("clave_prod")+" - "+rsR.getString("descripcion"));
                    }                    
                }
                
                
                rsR.close();
                st.close();
                con.desconectar();                  
            } catch (SQLException ex) {       

                JOptionPane.showMessageDialog(null, "Error al obtener datos del producto: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }  
            
            
            jtproductos.getColumnModel().getColumn(0).setMaxWidth(0);
            jtproductos.getColumnModel().getColumn(0).setMinWidth(0);
            jtproductos.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtproductos.getColumnModel().getColumn(0).setWidth(0);
            cargatabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigobarra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcompra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jcagranel = new javax.swing.JComboBox<>();
        txtmayoreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtventa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtminimo = new javax.swing.JTextField();
        txtcantmayoreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jccategoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jciva = new javax.swing.JCheckBox();
        txtieps = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcantpromo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtpreciopromo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblcampo1 = new javax.swing.JLabel();
        lblcampo2 = new javax.swing.JLabel();
        txtcampo1 = new javax.swing.JTextField();
        txtcampo2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtclavesat = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jlconceptosat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcprodcompuesto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        txtcb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edición de Producto");

        jPanel1.setBackground(new java.awt.Color(233, 233, 255));

        jPanel2.setBackground(new java.awt.Color(245, 244, 244));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Edición de Producto");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Producto:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código de Barras:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Precio Compra:");

        txtcompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcompraKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Agranel (Decimales):");

        jcagranel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        jcagranel.setToolTipText("Vender con valores decimales");

        txtmayoreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmayoreoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Precio Mayoreo:");

        txtventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtventaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Precio Venta:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Stock Minimo:");

        txtminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtminimoKeyTyped(evt);
            }
        });

        txtcantmayoreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantmayoreoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Cant. Min. Mayoreo:");

        jccategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jccategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Categoria:");

        jciva.setText("Costo con IVA");
        jciva.setToolTipText("Marcar la casilla si el costo del producto ya tiene iva");

        txtieps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtiepsKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("IEPS %:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Nota Si no desea dar promoción coloque 0 en las 2 casillas");

        txtcantpromo.setText("0");
        txtcantpromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantpromoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cantidad Minima Promoción:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Precio Promoción:");

        txtpreciopromo.setText("0");
        txtpreciopromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpreciopromoKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblcampo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblcampo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcampo1.setText("Campo1:");

        lblcampo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblcampo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcampo2.setText("Campo2:");

        jLabel18.setText("Clave para SAT:");

        txtclavesat.setEnabled(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jlconceptosat.setText("Concepto SAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtventa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmayoreo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcodigobarra)
                                .addComponent(txtproducto)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcagranel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcantmayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jciva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jccategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtieps, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtclavesat))
                            .addComponent(lblcampo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantpromo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpreciopromo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlconceptosat, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigobarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jcagranel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantmayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jccategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jciva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtieps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantpromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreciopromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtclavesat, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlconceptosat)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Generales", jPanel2);

        jPanel3.setBackground(new java.awt.Color(248, 246, 246));

        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Nota: Permite conformar un producto a partir de varios productos registrados.");

        jLabel4.setText("Es producto Compuesto:");

        jcprodcompuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

        jtproductos.getTableHeader().setReorderingAllowed(false) ;
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Prod", "Producto", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtproductos.setComponentPopupMenu(jPopupMenu1);
        jtproductos.setRowHeight(22);
        jtproductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtproductos);

        txtcb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcbKeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras.png"))); // NOI18N
        jButton2.setText("Cargar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        jLabel17.setText("Ejemplo: CANASTA BASICA  (HUEVO, LECHE, FRIJOL, ARROZ, ETC).");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcprodcompuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtcb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcprodcompuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Producto Compuesto", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompraKeyTyped
        // TODO add your handling code here:
        if(txtcompra.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtcompraKeyTyped

    private void txtventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtventaKeyTyped
        // TODO add your handling code here:
        if(txtventa.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtventaKeyTyped

    private void txtminimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminimoKeyTyped
        // TODO add your handling code here:
        if(txtminimo.getText().trim().length()>=4){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9'))){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtminimoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String clavesat=txtclavesat.getText().trim();
        String categoria=null;
        if (jccategoria.getSelectedItem().toString().equals("Selecciona..")) {
        }else{
            String[] arrayclave = jccategoria.getSelectedItem().toString().split("-");
            categoria = arrayclave[0];            
        } 
        
        if(txtproducto.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el producto. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtcompra.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el costo de compra. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtventa.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el costo de venta. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtmayoreo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el costo de mayoreo. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtcantmayoreo.getText().trim().equals("")){           
            JOptionPane.showMessageDialog(null, "Error falta ingresar la cantidad minima para venta al mayoreo. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtminimo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar la cantidad minima de stock. ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtpreciopromo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el precio de promoción SI NO DESEA DAR PROMOCION SOLO COLOQUE 0 ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtcantpromo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar la cantidad para la promoción SI NO DESEA DAR PROMOCION SOLO COLOQUE 0", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(txtieps.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Error falta ingresar el IEPS", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
                float costoventa=Float.parseFloat(txtventa.getText().trim()); 
                float costomayoreo=Float.parseFloat(txtmayoreo.getText().trim());  
                if(jciva.isSelected()){
                    costoventa=(float) (costoventa/1.16);
                    costomayoreo=(float) (costomayoreo/1.16);
                }
                
             if(clavesat.equals("")){
                clavesat="0";
             }   
            conex con=new conex();
            try {
                String producto=txtproducto.getText().trim();
                //https://es.stackoverflow.com/questions/32488/espacios-en-blanco
                //La expresión regular " {2,}" coincide con 2 o más espacios consecutivos, lo cual permite reemplazarlo por 1 solo
                producto = producto.replaceAll(" {2,}"," ");
                String myQuery = "update tc_productos set idr_concep_sat='"+clavesat+"', campo1='"+txtcampo1.getText().trim()+"', campo2='"+txtcampo2.getText().trim()+"', ieps='"+txtieps.getText().trim()+"', agranel='"+jcagranel.getSelectedItem().toString()+"', precio_promocion='"+txtpreciopromo.getText().trim()+"', cantidad_promocion='"+txtcantpromo.getText().trim()+"', cantidad_mayoreo='"+txtcantmayoreo.getText().trim()+"', precio_mayoreo='"+costomayoreo+"', idrcategoria="+categoria+", codigo_barras='"+txtcodigobarra.getText().trim()+"', nombre_producto='"+producto+"', precio_compra='"+txtcompra.getText().trim()+"', precio_venta='"+costoventa+"', cantidad_minima='"+txtminimo.getText().trim()+"' where idproducto='"+id_prod+"'";
                System.out.println(""+myQuery);
                Statement st = con.getConnection().createStatement();
                st.executeUpdate(myQuery);
                st.close();
                con.desconectar();
                Productos.cargartabla();
                JOptionPane.showMessageDialog(null, "El producto se modifico correctamente. ", "Producto modificado", JOptionPane.PLAIN_MESSAGE);
                dispose();
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Error al modificar el producto: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmayoreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmayoreoKeyTyped
        // TODO add your handling code here:
        if(txtmayoreo.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtmayoreoKeyTyped

    private void txtcantmayoreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantmayoreoKeyTyped
        // TODO add your handling code here:
        if(txtcantmayoreo.getText().trim().length()>=6){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9'))){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtcantmayoreoKeyTyped

    private void txtcantpromoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantpromoKeyTyped
        // TODO add your handling code here:
         if(txtcantpromo.getText().trim().length()>=6){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9'))){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtcantpromoKeyTyped

    private void txtpreciopromoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciopromoKeyTyped
        // TODO add your handling code here:
         if(txtpreciopromo.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtpreciopromoKeyTyped

    private void txtiepsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiepsKeyTyped
        // TODO add your handling code here:
        if(txtieps.getText().trim().length()>=5){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
                evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtiepsKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!txtcb.getText().trim().equals("")){
            cargar_producto(txtcb.getText().trim(),"CB");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcbKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
            if(!txtcb.getText().trim().equals("")){
                cargar_producto(txtcb.getText().trim(),"CB");
            }
        }
    }//GEN-LAST:event_txtcbKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();  
          int fila=-1;
          fila=jtproductos.getSelectedRow();
          if(fila!=-1){              
                modelo.removeRow(fila);                              
          }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un producto de la tabla.","Alerta",JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        catalogo_productosCompuesto dialog = new catalogo_productosCompuesto(f, true);
        dialog.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        conex con=new conex();
            try {
                String myQuery = "update tc_productos set prodcompuesto='"+jcprodcompuesto.getSelectedItem()+"' where idproducto='"+id_prod+"'";
                System.out.println(""+myQuery);
                Statement st = con.getConnection().createStatement();
                st.executeUpdate(myQuery);
                
                myQuery="delete from tc_prod_compuesto where Idr_productoPrimario='"+id_prod+"'";
                st.executeUpdate(myQuery);
                    
                for(int fila=0; fila<jtproductos.getRowCount(); fila++){               
                    String idprodsecundario=jtproductos.getValueAt(fila, 0).toString();              
                    String cantidad=jtproductos.getValueAt(fila, 2).toString();              
                    myQuery="insert into tc_prod_compuesto (Idr_productoPrimario,Id_prod_secundario,cant_utiliza) values('"+id_prod+"','"+idprodsecundario+"','"+cantidad+"')";
                    st.executeUpdate(myQuery);
                }
                
                
                st.close();
                con.desconectar();
                Productos.cargartabla();
                JOptionPane.showMessageDialog(null, "El producto se modifico correctamente. ", "Producto modificado", JOptionPane.PLAIN_MESSAGE);
                dispose();
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Error al modificar el producto: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            Frame f = JOptionPane.getFrameForComponent(this);
            claveproductosSAT ventaas=new claveproductosSAT(f,true);
            ventaas.show();
        //claveproductosSAT claves=new claveproductosSAT();
        //claves.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EdicionProducto dialog = new EdicionProducto(new javax.swing.JFrame(), true,"0");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcagranel;
    private javax.swing.JComboBox<String> jccategoria;
    private javax.swing.JCheckBox jciva;
    private javax.swing.JComboBox<String> jcprodcompuesto;
    private javax.swing.JLabel jlconceptosat;
    private static javax.swing.JTable jtproductos;
    private javax.swing.JLabel lblcampo1;
    private javax.swing.JLabel lblcampo2;
    private javax.swing.JTextField txtcampo1;
    private javax.swing.JTextField txtcampo2;
    private javax.swing.JTextField txtcantmayoreo;
    private javax.swing.JTextField txtcantpromo;
    public static javax.swing.JTextField txtcb;
    public static javax.swing.JTextField txtclavesat;
    private javax.swing.JTextField txtcodigobarra;
    private javax.swing.JTextField txtcompra;
    private javax.swing.JTextField txtieps;
    private javax.swing.JTextField txtmayoreo;
    private javax.swing.JTextField txtminimo;
    private javax.swing.JTextField txtpreciopromo;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtventa;
    // End of variables declaration//GEN-END:variables

    public void cargarcategorias() {
        jccategoria.removeAllItems();
        jccategoria.addItem("Selecciona..");     
        conex con = new conex();
        ResultSet rs = null;
        String myQuery = "SELECT * from tc_categorias where estatus=1";

        try {
            Statement st = con.getConnection().createStatement();
            rs = st.executeQuery(myQuery);
            while (rs.next()) {
                jccategoria.addItem(rs.getString("Idcategoria") + "-" + rs.getString("nombre"));
            }
            
            rs = st.executeQuery("select parametro from to_parametros where clave='campo1'");
            while (rs.next()) {
                lblcampo1.setText(rs.getString("parametro"));
            }
            
            rs = st.executeQuery("select parametro from to_parametros where clave='campo2'");
            while (rs.next()) {
                lblcampo2.setText(rs.getString("parametro"));
            }
            
            rs.close();
            st.close();
            con.desconectar();
        } catch (SQLException ex) {
        }

    }


public static void cargar_producto(String producto_code,String tipobusqueda){
        DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();          
        String codigo_barras=producto_code;
        conex con=new conex();          
        ResultSet rs = null;   
        String myQuery="";
        if(tipobusqueda.equals("CB")){
            myQuery = "SELECT * FROM tc_productos WHERE codigo_barras='"+codigo_barras+"' and estatus=1 and prodcompuesto='NO'";
        }
        if(tipobusqueda.equals("ID")){
            myQuery = "SELECT * FROM tc_productos WHERE idproducto='"+codigo_barras+"' and estatus=1 and prodcompuesto='NO'"; //el estatus es producto comun
        }        
        //System.out.println(""+myQuery);
        try {  
            Statement st = con.getConnection().createStatement();
            rs = st.executeQuery(myQuery);
           
            String codigobarra="",producto="";          
            String id="";
            boolean existe=false;           
            if(rs.next()) {                                 
                producto=rs.getString("nombre_producto");                
                id=rs.getString("idproducto");
                existe=true;                                                           
            }
           
            rs.close(); 
            st.close();
            con.desconectar();   
                                   
            if(existe){                
                   modelo.addRow(new Object[]{id,producto,"1"});                
            }
             
        } catch (SQLException ex) {
        }
        
        
        
        txtcb.setText("");        
        txtcb.requestFocus();
    }
    


public void cargatabla(){
        vaciartabla();
        conex conlocal=new conex();                   
        ResultSet rs = null;
        DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();  
     
        try {
            Statement st = conlocal.getConnection().createStatement();
            String consul="select Id_prod_secundario,nombre_producto,cant_utiliza from tc_prod_compuesto,tc_productos where idproducto=Id_prod_secundario and Idr_productoPrimario='"+id_prod+"'";
            System.out.println(""+consul);
            rs = st.executeQuery(consul);
            while(rs.next()) {                     
                modelo.addRow(new Object[]{""+rs.getString("Id_prod_secundario"),""+rs.getString("nombre_producto"),""+rs.getString("cant_utiliza")});
            }
            rs.close();
            conlocal.desconectar();
        } catch (SQLException ex) {
            
        }
        
    }
    
    
    public void vaciartabla(){
        DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();         
        for (int i = 0; i < jtproductos.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }    
    } 

    
}
