/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdialog;

import conexion.conex;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author desarrollo8
 */
public class Privilegios extends javax.swing.JDialog {

    /**
     * Creates new form Privilegios
     */
    public Privilegios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jcventas = new javax.swing.JCheckBox();
        jcclientes = new javax.swing.JCheckBox();
        jcproveedores = new javax.swing.JCheckBox();
        jcinventarios = new javax.swing.JCheckBox();
        jcacierre = new javax.swing.JCheckBox();
        jcreportes = new javax.swing.JCheckBox();
        jcrespaldos = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jcproductos = new javax.swing.JCheckBox();
        jcusuarios = new javax.swing.JCheckBox();
        jccategorias = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jccotizaciones = new javax.swing.JCheckBox();
        jcagenda = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jprivilegio = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jctraspasos = new javax.swing.JCheckBox();
        jcfacturacion = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Privilegios a Usuarios");

        jPanel1.setBackground(new java.awt.Color(249, 247, 247));

        jPanel2.setBackground(new java.awt.Color(247, 243, 243));

        jcventas.setText("Ventas");

        jcclientes.setText("Clientes");

        jcproveedores.setText("Proveedores");

        jcinventarios.setText("inventarios");

        jcacierre.setText("Cierre de Caja");

        jcreportes.setText("Reportes");

        jcrespaldos.setText("Respaldo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Catálogos");

        jcproductos.setText("Productos");

        jcusuarios.setText("Usuarios");

        jccategorias.setText("Categorias");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Utilerias");

        jccotizaciones.setText("Cotizaciones");

        jcagenda.setText("Agenda");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Selecciona Usuario:");

        jprivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..", "OPERADOR", "ALMACEN", "COMPRAS" }));
        jprivilegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprivilegioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jctraspasos.setText("Traspasos");

        jcfacturacion.setText("Facturación");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jctraspasos)
                            .addComponent(jLabel2)
                            .addComponent(jcventas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcinventarios)
                            .addComponent(jcacierre)
                            .addComponent(jcreportes)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jprivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcproveedores)
                                    .addComponent(jcrespaldos))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jccotizaciones)
                                        .addGap(32, 32, 32)
                                        .addComponent(jcagenda))
                                    .addComponent(jcfacturacion))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcclientes)
                        .addGap(51, 51, 51)
                        .addComponent(jcproductos)
                        .addGap(44, 44, 44)
                        .addComponent(jcusuarios)
                        .addGap(42, 42, 42)
                        .addComponent(jccategorias)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcventas)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcclientes)
                    .addComponent(jcproductos)
                    .addComponent(jcusuarios)
                    .addComponent(jccategorias))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcproveedores)
                    .addComponent(jcfacturacion))
                .addGap(18, 18, 18)
                .addComponent(jcinventarios)
                .addGap(18, 18, 18)
                .addComponent(jcacierre)
                .addGap(18, 18, 18)
                .addComponent(jcreportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jctraspasos)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcrespaldos)
                    .addComponent(jccotizaciones)
                    .addComponent(jcagenda))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Asignar Privilegios a los usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jprivilegio.getSelectedItem().toString().equals("Selecciona..")){
            String ventas="0",catcliente="0",catprod="0",catusuario="0",catcateg="0",proveedores="0",inventarios="0",cierre="0",reportes="0";
            String traspasos="0",respaldo="0",cotizaciones="0",agenda="0",cierrecaja="0",facturacion="0";
            if(jcventas.isSelected()==true){
                ventas="1";
            }
            if(jcclientes.isSelected()==true){
                catcliente="1";
            }
            if(jcproductos.isSelected()==true){
                catprod="1";
            }
            if(jccategorias.isSelected()==true){
                catcateg="1";
            }
            if(jcproveedores.isSelected()==true){
                proveedores="1";
            }
            if(jcinventarios.isSelected()==true){
                inventarios="1";
            }
            if(jcacierre.isSelected()==true){
                cierrecaja="1";
            }
            if(jcreportes.isSelected()==true){
                reportes="1";
            }
            if(jctraspasos.isSelected()==true){
                traspasos="1";
            }
            if(jcrespaldos.isSelected()==true){
                respaldo="1";
            }
            if(jccotizaciones.isSelected()==true){
                cotizaciones="1";
            }
            if(jcagenda.isSelected()==true){
                agenda="1";
            }
            if(jcfacturacion.isSelected()==true){
                facturacion="1";
            }
             conex con=new conex();  
            try {
                String myQuery = "update privilegios set ventas='"+ventas+"',catcliente='"+catcliente+"',"
                + "catprod='"+catprod+"',catusuario='"+catusuario+"',catcateg='"+catcateg+"',"
                + "proveedores='"+proveedores+"',inventarios='"+inventarios+"',reportes='"+reportes+"',"
                + "respaldo='"+respaldo+"',cotizaciones='"+cotizaciones+"', agenda='"+agenda+"', "
                + "traspasos='"+traspasos+"', cierrecaja='"+cierrecaja+"', facturacion='"+facturacion+"' where usuario='"+jprivilegio.getSelectedItem().toString()+"'";
                System.out.println(""+myQuery);
                Statement st = con.getConnection().createStatement();
                st.executeUpdate(myQuery);
                st.close();
                con.desconectar();                  
                JOptionPane.showMessageDialog(null, "El privilegio se modifico correctamente. ", "registrado", JOptionPane.PLAIN_MESSAGE);
                dispose();
            } catch (SQLException ex) {       

                JOptionPane.showMessageDialog(null, "Error al actualizar el privilegio: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }                         
        }else{
          JOptionPane.showMessageDialog(null, "Seleccione un usuario. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jprivilegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprivilegioActionPerformed
        // TODO add your handling code here:
        String user=jprivilegio.getSelectedItem().toString();
        System.out.println(user);
        if(user.equals("Selecciona..")){            
            jcventas.setSelected(false);
            jcclientes.setSelected(false);
            jcproductos.setSelected(false);
            jccategorias.setSelected(false);
            jcproveedores.setSelected(false);
            jcinventarios.setSelected(false);
            jcacierre.setSelected(false);
            jcreportes.setSelected(false);
            jctraspasos.setSelected(false);
            jcrespaldos.setSelected(false);
            jccotizaciones.setSelected(false);
            jcagenda.setSelected(false);
        }else{
         conex con=new conex();  
            try {
                String myQuery = "select * from privilegios where usuario='"+user+"'";
                System.out.println(""+myQuery);
                Statement st = con.getConnection().createStatement();
                ResultSet rs=st.executeQuery(myQuery);
                while(rs.next()){
                    if(rs.getString("ventas").equals("1")){
                        jcventas.setSelected(true);
                    }else{
                        jcventas.setSelected(false);
                    }
                    if(rs.getString("catcliente").equals("1")){
                        jcclientes.setSelected(true);
                    }else{
                        jcclientes.setSelected(false);
                    }
                    if(rs.getString("catprod").equals("1")){
                        jcproductos.setSelected(true);
                    }else{
                        jcproductos.setSelected(false);
                    }
                    if(rs.getString("catusuario").equals("1")){
                        jcusuarios.setSelected(true);
                    }else{
                        jcusuarios.setSelected(false);
                    }
                    if(rs.getString("catcateg").equals("1")){
                        jccategorias.setSelected(true);
                    }else{
                        jccategorias.setSelected(false);
                    }
                    if(rs.getString("proveedores").equals("1")){
                        jcproveedores.setSelected(true);
                    }else{
                        jcproveedores.setSelected(false);
                    }
                    if(rs.getString("inventarios").equals("1")){
                        jcinventarios.setSelected(true);
                    }else{
                        jcinventarios.setSelected(false);
                    }
                    
                    if(rs.getString("reportes").equals("1")){
                        jcreportes.setSelected(true);
                    }else{
                        jcreportes.setSelected(false);
                    }
                    if(rs.getString("respaldo").equals("1")){
                        jcrespaldos.setSelected(true);
                    }else{
                        jcrespaldos.setSelected(false);
                    }
                    if(rs.getString("cotizaciones").equals("1")){
                        jccotizaciones.setSelected(true);
                    }else{
                        jccotizaciones.setSelected(false);
                    }
                    if(rs.getString("agenda").equals("1")){
                        jcagenda.setSelected(true);
                    }else{
                        jcagenda.setSelected(false);
                    }
                    if(rs.getString("traspasos").equals("1")){
                        jctraspasos.setSelected(true);
                    }else{
                        jctraspasos.setSelected(false);
                    }
                    if(rs.getString("cierrecaja").equals("1")){
                        jcacierre.setSelected(true);
                    }else{
                        jcacierre.setSelected(false);
                    }
                    if(rs.getString("facturacion").equals("1")){
                        jcfacturacion.setSelected(true);
                    }else{
                        jcfacturacion.setSelected(false);
                    }
                }
                st.close();
                con.desconectar();                  
                                
            } catch (SQLException ex) {       

                JOptionPane.showMessageDialog(null, "Error al obtener los privilegio: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        
        }
    }//GEN-LAST:event_jprivilegioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Privilegios dialog = new Privilegios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcacierre;
    private javax.swing.JCheckBox jcagenda;
    private javax.swing.JCheckBox jccategorias;
    private javax.swing.JCheckBox jcclientes;
    private javax.swing.JCheckBox jccotizaciones;
    private javax.swing.JCheckBox jcfacturacion;
    private javax.swing.JCheckBox jcinventarios;
    private javax.swing.JCheckBox jcproductos;
    private javax.swing.JCheckBox jcproveedores;
    private javax.swing.JCheckBox jcreportes;
    private javax.swing.JCheckBox jcrespaldos;
    private javax.swing.JCheckBox jctraspasos;
    private javax.swing.JCheckBox jcusuarios;
    private javax.swing.JCheckBox jcventas;
    private javax.swing.JComboBox<String> jprivilegio;
    // End of variables declaration//GEN-END:variables
}
