/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jdialog;
import ClasesDAO.Devoluciones;
import ClasesDAO.Ticket;
import ClasesDAO.TicketVenta;
import ClasesDAO.accesoSistema;
import com.mysql.jdbc.PreparedStatement;
import conexion.conex;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jinternalPanel.Ventas;
/**
 *
 * @author desarrollo8
 */
public class ReporteDiarioVentasDevoluciones extends javax.swing.JDialog {
private static TableRowSorter<TableModel> sorter;
    /**
     * Creates new form ReporteDiarioVentasDevoluciones
     */
    public ReporteDiarioVentasDevoluciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        Calendar c2 = new GregorianCalendar();
        txtfecha.setCalendar(c2);
        cargartabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlfolio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfolios = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtproductos = new javax.swing.JTable();
        jlcajero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jlmonto = new javax.swing.JLabel();
        txtfecha = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlproducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlcantidad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdevolver = new javax.swing.JTextField();
        txtidventa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas del día");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(233, 233, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Ventas del día");

        jlfolio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlfolio.setText("Folio:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");

        jtfolios.getTableHeader().setReorderingAllowed(false);
        jtfolios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Folio", "Monto", "Hora", "Cajero", "Consecutivo Diario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtfolios.setRowHeight(20);
        jtfolios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtfolios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfoliosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtfolios);

        jtproductos.getTableHeader().setReorderingAllowed(false);
        jtproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Producto", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtproductosMouseClicked(evt);
            }
        });
        jtproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtproductosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtproductos);

        jlcajero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlcajero.setText("Cajero:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Reimprimir Folio");

        txtBusqueda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton1.setText("Impimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlmonto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlmonto.setText("Monto:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto_bajo.png"))); // NOI18N
        jButton3.setText("Devolver Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto:");

        jlproducto.setText("-");

        jLabel5.setText("Cantidad:");

        jlcantidad.setText("-");

        jLabel9.setText("Cant. Devolver:");

        txtdevolver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdevolverKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdevolverKeyTyped(evt);
            }
        });

        txtidventa.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Dev. de Ticket");

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto_bajo.png"))); // NOI18N
        jButton4.setText("Devolver Venta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlfolio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlcajero)
                        .addGap(11, 11, 11)
                        .addComponent(jlmonto))
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel9)
                            .addComponent(txtdevolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
        txtBusqueda.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrar();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrar();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrar();
            }
        });
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void jtfoliosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfoliosMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount() == 1) {
            String folio=jtfolios.getValueAt(jtfolios.getSelectedRow(), 1).toString();
            String monto=jtfolios.getValueAt(jtfolios.getSelectedRow(), 2).toString();
            String cajero=jtfolios.getValueAt(jtfolios.getSelectedRow(), 4).toString();
            jlfolio.setText("Folio: "+folio);
            jlmonto.setText("Monto: $"+monto);
            jlcajero.setText("Cajero: "+cajero);
            cargartablaproductos(folio);
        }
    }//GEN-LAST:event_jtfoliosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila=-1;
        fila=jtfolios.getSelectedRow();
        if(fila!=-1){
            String id=jtfolios.getValueAt(jtfolios.getSelectedRow(),1).toString();
            
            TicketVenta ticketpdf=new TicketVenta();
            ticketpdf.imprimirticket(id+"","IMPPVT");
            //Ticket imprime=new Ticket();
            //imprime.ReImprimirDocumento(id);

        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un folio de la Tabla","Alerta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cargartabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtproductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtproductosKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            String id=jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString();
            String producto=jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString();
            String cantidad=jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString();
            jlproducto.setText(""+producto);
            jlcantidad.setText(""+cantidad);
            txtidventa.setText(""+id);    
        }else{
        }
    }//GEN-LAST:event_jtproductosKeyPressed

    private void jtproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtproductosMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 2) {
            String id=jtproductos.getValueAt(jtproductos.getSelectedRow(), 0).toString();
            String producto=jtproductos.getValueAt(jtproductos.getSelectedRow(), 1).toString();
            String cantidad=jtproductos.getValueAt(jtproductos.getSelectedRow(), 2).toString();
            jlproducto.setText(""+producto);
            jlcantidad.setText(""+cantidad);
            txtidventa.setText(""+id);         
            txtdevolver.requestFocus();
         }
    }//GEN-LAST:event_jtproductosMouseClicked

    private void txtdevolverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevolverKeyTyped
        // TODO add your handling code here:
         if(txtdevolver.getText().trim().length()>=5){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
               evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtdevolverKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        registrar();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.println("salida de devoluciones");
        Ventas.txtproducto.requestFocus();
    }//GEN-LAST:event_formWindowClosing

    private void txtdevolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevolverKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registrar();
        }
    }//GEN-LAST:event_txtdevolverKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo=(DefaultTableModel) jtfolios.getModel();
        int fila=-1;
        fila=jtfolios.getSelectedRow();
        if(fila!=-1){
            String folio=jtfolios.getValueAt(jtfolios.getSelectedRow(),0).toString();
            String nofolio=jtfolios.getValueAt(jtfolios.getSelectedRow(),1).toString();
            conex con=new conex();
            try {
                String myQuery = "select idventa,cantidad from to_ventas where folio='"+nofolio+"'";
                System.out.println(""+myQuery);
                ResultSet rsR = null;
                Statement st = con.getConnection().createStatement();
                rsR = st.executeQuery(myQuery);
                Devoluciones devolver =new Devoluciones();
                while(rsR.next()) {   
                    System.out.println(""+rsR.getString("idventa"));
                    devolver.devolucionfolio(rsR.getString("idventa"),rsR.getFloat("cantidad"));
                }
                myQuery="update to_folios set estatus=2, monto_total=0, fecha_devolucion=now(), usuario_devolucion='"+accesoSistema.nombreuser+"' where idfolio='"+folio+"'";
                st.executeUpdate(myQuery);
                
                myQuery="update to_cierre_caja set no_ventas=no_ventas-1 where id_cierre_caja=1";
                st.executeUpdate(myQuery);
                if(!accesoSistema.nombrecaja.equals("")){
                    myQuery = "update to_cierre_caja set no_ventas=no_ventas-1 WHERE caja ='"+accesoSistema.nombrecaja+"'";        
                    st.executeUpdate(myQuery);  
                }		 
           
                rsR.close();
                st.close();
                con.desconectar();
                JOptionPane.showMessageDialog(null, "La devolución se realizo correctamente.", "Devolución Correcta", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Error al realizar la devolucion: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargartabla();
            vaciartablaprod();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un folio de la tabla principal.","Alerta",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDiarioVentasDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDiarioVentasDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDiarioVentasDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDiarioVentasDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteDiarioVentasDevoluciones dialog = new ReporteDiarioVentasDevoluciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     public void vaciartabla(){
            DefaultTableModel modelo=(DefaultTableModel) jtfolios.getModel();         
            for (int i = 0; i < jtfolios.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
public void cargartabla(){    
        vaciartabla();
        Date fecha=txtfecha.getDate();
        SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
        String fechaformateadas=fechaformateada.format(fecha);
        
        DefaultTableModel modelo=(DefaultTableModel) jtfolios.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;   
        int i=1;
        String myQuery = "select idfolio,no_folio,(monto_total+iva) as monto_total, HOUR(fecha_movimiento) as hora , minute(fecha_movimiento) as minu,usuario_registro from to_folios where tipo_movimiento='VENTA' and fecha_movimiento>='"+fechaformateadas+" 00:00:00' and fecha_movimiento<='"+fechaformateadas+" 23:59:59' and estatus=1 order by idfolio desc";
               System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("idfolio"),rsR.getString("no_folio"),rsR.getString("monto_total"),rsR.getString("hora")+":"+rsR.getString("minu"),rsR.getString("usuario_registro"),i+""});                        
                            i++;
                   }
                   sorter = new TableRowSorter<TableModel>(modelo);
                   jtfolios.setRowSorter(sorter);
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
            jtfolios.getColumnModel().getColumn(0).setMaxWidth(0);
            jtfolios.getColumnModel().getColumn(0).setMinWidth(0);
            jtfolios.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtfolios.getColumnModel().getColumn(0).setWidth(0); 
    }    
    
 public void vaciartablaprod(){
            DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();         
            for (int i = 0; i < jtproductos.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
public void cargartablaproductos(String folio){    
        vaciartablaprod();
        DefaultTableModel modelo=(DefaultTableModel) jtproductos.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select idventa,to_ventas.idproducto,cantidad,(total-descuento) as total,nombre_producto from to_ventas,tc_productos where to_ventas.idproducto=tc_productos.idproducto and folio='"+folio+"'";
               System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("idventa"),rsR.getString("nombre_producto"),rsR.getString("cantidad"),rsR.getString("total")});                        
                   }                                      
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
        jtproductos.getColumnModel().getColumn(0).setMaxWidth(0);
        jtproductos.getColumnModel().getColumn(0).setMinWidth(0);
        jtproductos.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtproductos.getColumnModel().getColumn(0).setWidth(0);
              
    }    
   private void filtrar() {
        
         RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("(?i)"+txtBusqueda.getText(),1,2);
        }catch (java.util.regex.PatternSyntaxException e) {
        }
        sorter.setRowFilter(rf);
    }

   
   public String contra(String mensaje,String titulo){
    String password = "";
    JPasswordField passwordField = new JPasswordField();
    Object[] obj = {mensaje+":\n\n", passwordField};
    Object stringArray[] = {"OK","Cancel"};
    passwordField.requestFocus();
    if (JOptionPane.showOptionDialog(null, obj, titulo,JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
    null, stringArray, obj) == JOptionPane.YES_OPTION)
    {
    password = new String(passwordField.getPassword());
    }
    System.out.println("contra: "+password);
    
    
        conex cn = new conex();
	String sql="SELECT parametro from to_parametros where clave='CLAVEADMIN'";
	String clave="";
	PreparedStatement pstm100;
	try {
		pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
		ResultSet rs100 = (ResultSet) pstm100.executeQuery();
                while (rs100.next()) {
                    clave=rs100.getString("parametro");
	    	
		}
	    rs100.close();
            pstm100.close();
            cn.desconectar();
	} catch (SQLException e2) {
		// TODO Auto-generated catch block
		e2.printStackTrace();
	}
    
    
    String valida="NOPROCESAR";
    if(password.equals(clave)){
        valida="PROCESARVENTA";
    }
    System.out.println("contra: "+valida);
    return valida;    
}
   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlcajero;
    private javax.swing.JLabel jlcantidad;
    private javax.swing.JLabel jlfolio;
    private javax.swing.JLabel jlmonto;
    private javax.swing.JLabel jlproducto;
    private javax.swing.JTable jtfolios;
    private javax.swing.JTable jtproductos;
    private static javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtdevolver;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtidventa;
    // End of variables declaration//GEN-END:variables

    public void registrar(){
        boolean validaadmin=true;
        String validaclave=contra("Introdusca la contraseña para aplicar devolución.","Devolución");
        //if(validaclave.equals("NOPROCESAR")){
        //    JOptionPane.showMessageDialog(null, "La contraseña no es correcta vuelva a intentarlo.", "Alerta", JOptionPane.ERROR_MESSAGE);
        //    validaadmin=false;
        //}
        
        float cantdevolver=Float.parseFloat(txtdevolver.getText().trim());
        float cantidadactual=Float.parseFloat(jlcantidad.getText().trim());
        String idventa=txtidventa.getText().trim();
        if(cantidadactual<cantdevolver){
            JOptionPane.showMessageDialog(null, "La cantidad a devolver no puede ser mayor a la actual.","Alerta",JOptionPane.ERROR_MESSAGE);
        }else if(validaclave.equals("NOPROCESAR")){
            JOptionPane.showMessageDialog(null, "La contraseña no es correcta vuelva a intentarlo.", "Alerta", JOptionPane.ERROR_MESSAGE);            
        }else{
            int opc=JOptionPane.showConfirmDialog(null, "¿Estas seguro de realizar la devolución?","Alerta",JOptionPane.INFORMATION_MESSAGE);
            if(opc==JOptionPane.OK_OPTION){
                Devoluciones devolver =new Devoluciones();
                boolean exito=devolver.devolucion(idventa,cantdevolver);
                if(exito==false){
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la devolución.", "Alerta", JOptionPane.ERROR_MESSAGE);                
                }
                cargartabla();
                cargartablaproductos(idventa);
                txtidventa.setText("");
                txtdevolver.setText("");
                jlproducto.setText("-");
                jlcantidad.setText("-");
            }
        }
    }
}
