/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jinternalPanel;

import ClasesDAO.Ticket;
import conexion.conex;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author desarrollo8
 */
public class ReporteGeneral extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteGeneral
     */
    public ReporteGeneral() {
        initComponents();
        Calendar c2 = new GregorianCalendar();
        txtfechaini.setCalendar(c2);
        txtfechafin.setCalendar(c2);
        
        Date fecha=txtfechaini.getDate();
        Date fecha2=txtfechafin.getDate();
        SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
        String fechaformateadas=fechaformateada.format(fecha);
        String fechafin=fechaformateada.format(fecha2);
        jlrango.setText("Del "+fechaformateadas+"  Al  "+fechafin);
        
        
        conex con=new conex();  
            try {
                String myQuery = "select * from tc_usuarios where estatus=1";
                System.out.println(""+myQuery);
                ResultSet rsR = null; 
                Statement st = con.getConnection().createStatement();
                rsR = st.executeQuery(myQuery);
                //cbcajero.addItem("Selecciona..");
                while(rsR.next()) {                                                                                              
                    cbcajero.addItem(rsR.getString("idusuario")+"-"+rsR.getString("nombre"));    
                }
                rsR.close();
                st.close();
                con.desconectar();                  
            } catch (SQLException ex) {       

                JOptionPane.showMessageDialog(null, "Error al obtener datos del producto: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }  
        
        
        cargarinformacion_ventas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlrango = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfechaini = new com.toedter.calendar.JDateChooser();
        txtfechafin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlmontototal = new javax.swing.JLabel();
        jlnumeroventas = new javax.swing.JLabel();
        jlventaspromedio = new javax.swing.JLabel();
        jlventasefectivo = new javax.swing.JLabel();
        jlventastarjeta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbcajero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jlentradaefectivo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlsalidaefectivo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlcreditocliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcorte = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Resumen de Ventas");

        jlrango.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlrango.setForeground(new java.awt.Color(102, 102, 102));
        jlrango.setText("Del                Al");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ventas Totales");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Número de Ventas");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ventas Promedio");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Del");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Al");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Ventas por Forma de Pago");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Efectivo");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tarjeta");

        jlmontototal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlmontototal.setForeground(new java.awt.Color(0, 51, 153));
        jlmontototal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlmontototal.setText("0.00");

        jlnumeroventas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlnumeroventas.setForeground(new java.awt.Color(0, 51, 153));
        jlnumeroventas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlnumeroventas.setText("0.00");

        jlventaspromedio.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlventaspromedio.setForeground(new java.awt.Color(0, 51, 153));
        jlventaspromedio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlventaspromedio.setText("0.00");

        jlventasefectivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlventasefectivo.setForeground(new java.awt.Color(0, 51, 153));
        jlventasefectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlventasefectivo.setText("0.00");

        jlventastarjeta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlventastarjeta.setForeground(new java.awt.Color(0, 51, 153));
        jlventastarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlventastarjeta.setText("0.00");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbcajero.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbcajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona.." }));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Cajero");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Entradas");

        jlentradaefectivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlentradaefectivo.setForeground(new java.awt.Color(0, 51, 153));
        jlentradaefectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlentradaefectivo.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Salidas");

        jlsalidaefectivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlsalidaefectivo.setForeground(new java.awt.Color(204, 0, 0));
        jlsalidaefectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlsalidaefectivo.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Credito");

        jlcreditocliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlcreditocliente.setForeground(new java.awt.Color(0, 51, 153));
        jlcreditocliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlcreditocliente.setText("0.00");

        jtcorte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Monto", "Observacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtcorte);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        jButton8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jButton8.setText("Exporar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlrango, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(316, 316, 316))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtfechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(49, 49, 49)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlnumeroventas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlmontototal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlventaspromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(cbcajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jlventastarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jlventasefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlentradaefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlsalidaefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlcreditocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlrango, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfechaini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfechafin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlventasefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlventastarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlmontototal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnumeroventas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlventaspromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlentradaefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlsalidaefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcreditocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargarinformacion_ventas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            Date fecha=txtfechaini.getDate();
            Date fecha2=txtfechafin.getDate();
            SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
            String fechaformateadas=fechaformateada.format(fecha);
            String fechafin=fechaformateada.format(fecha2);
            String total=jlmontototal.getText();
            String numventas=jlnumeroventas.getText();
            String promedio=jlventaspromedio.getText();
            String efectivo=jlventasefectivo.getText();
            String tarjetas=jlventastarjeta.getText();
            String entradas=jlentradaefectivo.getText();
            String salidas=jlsalidaefectivo.getText();
            String credito=jlcreditocliente.getText();
            
        Ticket imprime=new Ticket();
        imprime.Imprimirresumenventa(total,numventas,promedio,fechaformateadas,fechafin,efectivo,tarjetas,entradas,salidas,credito);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        Date fecha1=new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy hh-MM-ss");
        //formateador.format(fecha1);
        System.out.println(formateador.format(fecha1));
        System.out.println(fecha1.toLocaleString());
        File archivo;

        javax.swing.JFileChooser jF1= new javax.swing.JFileChooser();
        String ruta = "";
        try{
            if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){
                ruta = jF1.getSelectedFile().getAbsolutePath();
                //archivo = new File(ruta+""+formateador.format(fecha1)+".xls");
                archivo = new File(ruta+".xls");
                System.out.println(archivo);
                //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras...
                exportarjTable(jtcorte,archivo);
                JOptionPane.showMessageDialog(null, "El reporte se ha generado con exito", "Mensaje", JOptionPane.DEFAULT_OPTION);
            }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, "No se ha podido generar el archivo:"+ex, "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public void vaciartabla(){
            DefaultTableModel modelo=(DefaultTableModel) jtcorte.getModel();         
            for (int i = 0; i < jtcorte.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
    public void cargarinformacion_ventas(){
            vaciartabla();
            DefaultTableModel modelo=(DefaultTableModel) jtcorte.getModel();  
            
            Date fecha=txtfechaini.getDate();
            Date fecha2=txtfechafin.getDate();
            SimpleDateFormat fechaformateada = new SimpleDateFormat("yyyy-MM-dd");  
            String fechaformateadas=fechaformateada.format(fecha);
            String fechafin=fechaformateada.format(fecha2);
            jlrango.setText("Del "+fechaformateadas+"  Al  "+fechafin);
            
            String sql="";
            String cajero=cbcajero.getSelectedItem().toString();
            if(cajero.equals("Selecciona..")){
            }else{
                sql=" and id_usuario='"+id(cajero)+"'";
            }
            
            
            
            conex con=new conex();  
            float totalventas=0;
            float cantidadventas=0;
            try {
                double montoventas=0,montoentrada=0,montosalida=0,creditocliente=0;
                ResultSet rsR = null; 
                Statement st = con.getConnection().createStatement();
                double efecmix=0;
                double credmix=0;
                String myQuery="select sum(efectivo) as efe,sum(tarjeta) as tar from to_folios where fecha_movimiento>='"+fechaformateadas+" 00:00' and fecha_movimiento<='"+fechafin+" 23:59' and estatus=1 and tipo_movimiento='VENTA' and forma_pago='MIXTO'"+sql;
                System.out.println(""+myQuery);
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {                                                
                       efecmix=rsR.getDouble("efe");  
                       credmix=rsR.getDouble("tar");  
                         
                }
                
                myQuery="select sum(monto_total+iva) as total from to_folios where fecha_movimiento>='"+fechaformateadas+" 00:00' and fecha_movimiento<='"+fechafin+" 23:59' and estatus=1 and tipo_movimiento='VENTA' and forma_pago='EFECTIVO'"+sql;
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {                                                
                        jlventasefectivo.setText("$ "+Math.rint(((rsR.getDouble("total")+efecmix)*1000)/1000));   
                        modelo.addRow(new Object[]{"EFECTIVO",Math.rint(((rsR.getDouble("total")+efecmix)*1000)/1000),""});     
                }
                
                myQuery="select sum(monto_total+iva) as total from to_folios where fecha_movimiento>='"+fechaformateadas+" 00:00' and fecha_movimiento<='"+fechafin+" 23:59' and estatus=1 and tipo_movimiento='VENTA' and forma_pago='TARJETA'"+sql;
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {   
                        if(rsR.getString("total")==null && credmix==0){
                            jlventastarjeta.setText("$ 0.00");  
                            modelo.addRow(new Object[]{"TARJETA","0.00",""});                        
                        }else{
                            jlventastarjeta.setText("$ "+Math.rint(((rsR.getDouble("total")+credmix)*1000)/1000));                 
                            modelo.addRow(new Object[]{"TARJETA",Math.rint(((rsR.getDouble("total")+credmix)*1000)/1000),""});                        
                        }
                        
                }
                
                myQuery = "select sum(Monto) as total from th_abonos_cliente where Fecha>='"+fechaformateadas+" 00:00' and Fecha<='"+fechafin+" 23:59'";
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {       
                        jlcreditocliente.setText("$ "+Math.rint((rsR.getDouble("total")*1000)/1000));
                        modelo.addRow(new Object[]{"CREDITO CLIENTE",Math.rint((rsR.getDouble("total")*1000)/1000),""});     
                        creditocliente=rsR.getDouble("total");
                }
                
                myQuery = "select sum(monto) as total from th_entradasefectivo where fecha>='"+fechaformateadas+" 00:00' and fecha<='"+fechafin+" 23:59' and movimiento='ENTRADA'";
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {       
                        jlentradaefectivo.setText("$ "+Math.rint((rsR.getDouble("total")*1000)/1000));
                        modelo.addRow(new Object[]{"ENTRADA EFECTIVO",Math.rint((rsR.getDouble("total")*1000)/1000),""});                         
                        montoentrada=rsR.getDouble("total");
                }
                
                 myQuery = "select sum(monto) as total from th_entradasefectivo where fecha>='"+fechaformateadas+" 00:00' and fecha<='"+fechafin+" 23:59' and movimiento='SALIDA'";
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {       
                        jlsalidaefectivo.setText("$ "+Math.rint((rsR.getDouble("total")*1000)/1000));
                        modelo.addRow(new Object[]{"SALIDA EFECTIVO",Math.rint((rsR.getDouble("total")*1000)/1000),""});     
                        montosalida=rsR.getDouble("total");
                }
                
                modelo.addRow(new Object[]{"","",""});     
                modelo.addRow(new Object[]{"","",""});     
                
                                
                myQuery = "select sum(monto_total+iva) as total from to_folios where fecha_movimiento>='"+fechaformateadas+" 00:00' and fecha_movimiento<='"+fechafin+" 23:59' and estatus=1 and (forma_pago='EFECTIVO' or forma_pago='TARJETA') and tipo_movimiento='VENTA'"+sql;
                System.out.println(""+myQuery);                
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {                                                
                    System.out.println("entra actualziar total"); 
                        montoventas=rsR.getDouble("total");                        
                        totalventas=rsR.getFloat("total");
                }
                
                
                double total=(montoventas+montoentrada+creditocliente)-montosalida;
                jlmontototal.setText("$ "+Math.rint((total*1000)/1000));  
                modelo.addRow(new Object[]{"TOTAL:",Math.rint((total*1000)/1000),""});     
                rsR=null;
                myQuery="select count(idfolio) as ventas from to_folios where fecha_movimiento>='"+fechaformateadas+" 00:00' and fecha_movimiento<='"+fechafin+" 23:59' and estatus=1 and tipo_movimiento='VENTA'"+sql;
                rsR = st.executeQuery(myQuery);
                if(rsR.next()) {                                                
                        jlnumeroventas.setText(rsR.getString("ventas")); 
                        modelo.addRow(new Object[]{"NO. VENTAS:",rsR.getString("ventas"),""});     
                        cantidadventas=rsR.getFloat("ventas");
                }
                double promedio=totalventas/cantidadventas;
                promedio=Math.rint((promedio*1000)/1000);
                System.out.println(""+promedio+"    div"+totalventas+"/"+cantidadventas);
                jlventaspromedio.setText("$ "+promedio+"");
                
                modelo.addRow(new Object[]{"","",""});     
                modelo.addRow(new Object[]{"","",""});  
                modelo.addRow(new Object[]{"CONCEPTO ENTRADAS DE EFECTIVO","",""});  
                myQuery = "select fecha,monto,motivo from th_entradasefectivo where fecha>='"+fechaformateadas+" 00:00' and fecha<='"+fechafin+" 23:59' and movimiento='ENTRADA'";
                rsR = st.executeQuery(myQuery);
                while(rsR.next()) {                               
                        modelo.addRow(new Object[]{rsR.getString("fecha"),rsR.getString("monto"),rsR.getString("motivo")});                                                 
                }
                modelo.addRow(new Object[]{"","",""});  
                modelo.addRow(new Object[]{"CONCEPTO SALIDAS DE EFECTIVO","",""}); 
                 myQuery = "select fecha,monto,motivo from th_entradasefectivo where fecha>='"+fechaformateadas+" 00:00' and fecha<='"+fechafin+" 23:59' and movimiento='SALIDA'";
                rsR = st.executeQuery(myQuery);
                while(rsR.next()) {                               
                        modelo.addRow(new Object[]{rsR.getString("fecha"),rsR.getString("monto"),rsR.getString("motivo")});                                                                         
                }
                
               
                
                
                
                st.close();
                con.desconectar();                  
            } catch (SQLException ex) {       

                JOptionPane.showMessageDialog(null, "Error al obtener datos del ventas: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
            }  
    }

    private String id(String id){
        String ids=id;
        String[] temp=ids.split("-");
        for(int i=0;i<1;i++){
            ids=temp[i];
        }
    return ids;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcajero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlcreditocliente;
    private javax.swing.JLabel jlentradaefectivo;
    private javax.swing.JLabel jlmontototal;
    private javax.swing.JLabel jlnumeroventas;
    private javax.swing.JLabel jlrango;
    private javax.swing.JLabel jlsalidaefectivo;
    private javax.swing.JLabel jlventasefectivo;
    private javax.swing.JLabel jlventaspromedio;
    private javax.swing.JLabel jlventastarjeta;
    private javax.swing.JTable jtcorte;
    private com.toedter.calendar.JDateChooser txtfechafin;
    private com.toedter.calendar.JDateChooser txtfechaini;
    // End of variables declaration//GEN-END:variables


 public void exportarjTable(JTable tabla, File ficheroXLS) throws IOException {
        TableModel modelo = tabla.getModel();
        FileWriter fichero = new FileWriter(ficheroXLS);
        
        for(int i=0; i < modelo.getColumnCount(); i++) {
            fichero.write(modelo.getColumnName(i) + "\t");
        }
        fichero.write("\n");
        for(int i=0; i< modelo.getRowCount(); i++) {
            for(int j=0; j < modelo.getColumnCount(); j++) {
                String dato="";
                if(modelo.getValueAt(i,j)==null){
                }else{    
                dato=modelo.getValueAt(i,j).toString();
                }
                fichero.write(dato+"\t");
            }
            fichero.write("\n");
        }
        fichero.close();
    }
       
    
}
