/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;

import ClasesDAO.Ticket;
import ClasesDAO.TicketVenta;
import Utilerias.funciones;
import conexion.conex;
import java.awt.Frame;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import puntoventa.PantallaPrincipal;

/**
 *
 * @author desarrollo8
 */
public class AddProductos extends javax.swing.JInternalFrame {
static String idmesa="";
    /**
     * Creates new form AddProductos
     */
    public AddProductos(String id, String nombremesa) {
        idmesa=id;
        initComponents();
        txtmesa.setText(nombremesa);
        
        jtcomanda.getColumnModel().getColumn(1).setMaxWidth(680);
        jtcomanda.getColumnModel().getColumn(1).setMinWidth(180);
        jtcomanda.getColumnModel().getColumn(1).setPreferredWidth(180);
        jtcomanda.getColumnModel().getColumn(1).setWidth(180);
        
        
        jtcategorias.getColumnModel().getColumn(0).setMaxWidth(0);
        jtcategorias.getColumnModel().getColumn(0).setMinWidth(0);
        jtcategorias.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtcategorias.getColumnModel().getColumn(0).setWidth(0);        
        cargartablacateg();        
        cargartablacliente();
        cargartablamesero();
        
        jtcomanda.getColumnModel().getColumn(4).setMaxWidth(0);
        jtcomanda.getColumnModel().getColumn(4).setMinWidth(0);
        jtcomanda.getColumnModel().getColumn(4).setPreferredWidth(0);
        jtcomanda.getColumnModel().getColumn(4).setWidth(0); 
        
        jtcomanda.getColumnModel().getColumn(5).setMaxWidth(0);
        jtcomanda.getColumnModel().getColumn(5).setMinWidth(0);
        jtcomanda.getColumnModel().getColumn(5).setPreferredWidth(0);
        jtcomanda.getColumnModel().getColumn(5).setWidth(0);
        
        jtcomanda.getColumnModel().getColumn(6).setMaxWidth(0);
        jtcomanda.getColumnModel().getColumn(6).setMinWidth(0);
        jtcomanda.getColumnModel().getColumn(6).setPreferredWidth(0);
        jtcomanda.getColumnModel().getColumn(6).setWidth(0); 
        
        refreshinfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtmesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jccliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcmesero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtota = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlmonto = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        lbltotal = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jccantidad = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcategorias = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtprod = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtcomanda = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        jPanel2.setBackground(new java.awt.Color(247, 246, 246));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtmesa.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mesa:");

        jccliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cliente:");

        jcmesero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Mesero:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nota:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtmesa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jccliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtota, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jcmesero, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jcmesero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(247, 246, 246));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlmonto.setVisible(false);
        jlmonto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlmonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlmonto.setText("$0.00");

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 153, 51));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinero.png"))); // NOI18N
        jButton11.setText("PAGAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 0, 0));
        jButton14.setText("REGRESAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        lbltotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltotal.setText("$0.00");

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setText("IMPRIMIR CUENTA");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton17.setText("SEPARADOR");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlmonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jlmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(247, 246, 246));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("8");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setText("1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("2");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setText("3");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad");

        jccantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jccantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jccantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jccantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtcategorias.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtcategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categorias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcategorias.setRowHeight(40);
        jtcategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtcategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtcategorias);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(251, 249, 249));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtprod.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jtprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtprod.setCellSelectionEnabled(true);
        jtprod.setRowHeight(60);
        jtprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtprodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtprod);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono_libro.png"))); // NOI18N
        jButton12.setText("Solicitar Pedido");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jButton13.setText("Cancelar Todo");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(249, 247, 247));

        jtcomanda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtcomanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio", "Total", "Id", "idtemp", "Comentario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtcomanda.setRowHeight(34);
        jtcomanda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jtcomanda);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        jButton10.setText("Eliminar Producto");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton16.setText("Comentario");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jccantidad.setSelectedItem("7");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jccantidad.setSelectedItem("8");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jccantidad.setSelectedItem("9");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("1");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("2");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         jccantidad.setSelectedItem("3");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jtcategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcategoriasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
               String id=jtcategorias.getValueAt(jtcategorias.getSelectedRow(), 0).toString();
               cargarproductos(id);
          }
        
    }//GEN-LAST:event_jtcategoriasMouseClicked

    private void jtprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtprodMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 1) {
               int columna=jtprod.getSelectedColumn();
               int fila=jtprod.getSelectedRow();
               String dato=String.valueOf(jtprod.getValueAt(jtprod.getSelectedRow(),columna));
               System.out.println("Se ha hecho un click: "+dato);
               cargarprodventa(dato);
               refreshinfo();
               jccantidad.setSelectedIndex(0);
          }
    }//GEN-LAST:event_jtprodMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel modelo=(DefaultTableModel) jtcomanda.getModel();  
          int fila=-1;
          fila=jtcomanda.getSelectedRow();
          if(fila!=-1){
              String idtempcomanda=jtcomanda.getValueAt(jtcomanda.getSelectedRow(),5).toString();
              conex con=new conex();   
              ResultSet rsR = null;        
              String myQuery = "delete from rest_temp_venta where Idtemp="+idtempcomanda;
               System.out.println(""+myQuery);
               try {
                  Statement st = con.getConnection().createStatement();
                  st.executeUpdate(myQuery);
                  st.close();
                  con.desconectar();
                  refreshinfo();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: de categorias"+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }  
              
              
          }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un producto de la tabla.","Alerta",JOptionPane.ERROR_MESSAGE);
         }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:        
        jccliente.setSelectedIndex(0);
        jcmesero.setSelectedIndex(0);
        txtota.setText("");
       
        
        DefaultTableModel modelo=(DefaultTableModel) jtcomanda.getModel();         
        for (int i = 0; i < jtcomanda.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        } 
         conex con=new conex();   
         ResultSet rsR = null;        
         String myQuery = "delete from rest_temp_venta where idrmesa="+idmesa;
               //System.out.println(""+myQuery);
               try {
                  Statement st = con.getConnection().createStatement();
                  st.executeUpdate(myQuery);
                  st.close();
                  con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: de categorias"+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }                 
        refreshinfo();
        statusmesa("LIBRE");
    
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
        statusmesa("OCUPADA");
        //MANDAR A IMPRIMIR LOS PLATILLOS
        Ticket imprimir=new Ticket();
        imprimir.ImprimirComanda(idmesa);
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         PantallaPrincipal.escritorio.removeAll();
         Comandera rest=new Comandera();        
            rest.setResizable(true);
            rest.setClosable(true);
            PantallaPrincipal.escritorio.add(rest);
            rest.show();
            //extiende al maximo la jinternal frame
            try {
                rest.setMaximum(true);
            } catch (PropertyVetoException ex) {               
            }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        String cliente=jccliente.getSelectedItem().toString();
        String mesero=jcmesero.getSelectedItem().toString();
        
    if(cliente.equals("")){
        cliente="0";
    }else{
        cliente=obtenidcliente(cliente);
    }
    
    if(mesero.equals("")){
        mesero="0";
    }else{
        mesero=obtenidcliente(mesero);
    }
        System.out.println("MESERO:"+mesero);
    
    int numprod=jtcomanda.getRowCount();
    if(numprod>0){
        ArrayList productos=new ArrayList();
        for(int fila=0; fila<jtcomanda.getRowCount(); fila++){
               //id    codigobarras   precioventa   cantidad   totalprod  descriprod   ieps
               productos.add(jtcomanda.getValueAt(fila, 4).toString()+"@NO@"+jtcomanda.getValueAt(fila, 2).toString()+"@"+jtcomanda.getValueAt(fila, 0).toString()+"@"+jtcomanda.getValueAt(fila, 3).toString()+"@"+jtcomanda.getValueAt(fila, 1).toString()+"@"+"0");               
       }
        
        int cant=jlmonto.getText().trim().length();
        String monto=jlmonto.getText().trim().substring(1, cant); //se quita el caracter $        
        double monto_final=Float.parseFloat(monto);
        double ieps=0;
        Frame f = JOptionPane.getFrameForComponent(this);
        double iva=obteniva();
        double subtotal=monto_final;
        monto_final=monto_final+(monto_final*iva);
        funciones redondeo=new funciones();
        monto_final=redondeo.redondearDecimales(monto_final,2);
        monto_final=monto_final+ieps;
        //monto_final=Math.rint((monto_final*1000)/1000);//redondea los numeros
        
        Cobrar_ventaRestaurant venta=new Cobrar_ventaRestaurant(f,true,monto_final,productos,subtotal,cliente,ieps,idmesa,mesero);
        venta.show();
    }else{
        JOptionPane.showMessageDialog(null, "No hay productos en la venta. ", "Error al registrar venta", JOptionPane.ERROR_MESSAGE);
       
    }
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
        
        String montototal=lbltotal.getText().trim();
        int numprod=jtcomanda.getRowCount();
        if(numprod>0){
            ArrayList productos=new ArrayList();
            for(int fila=0; fila<jtcomanda.getRowCount(); fila++){
                   //   precioventa   cantidad   totalprod  descriprod        
                   String canti=jtcomanda.getValueAt(fila, 0).toString();
                   if(canti.equals("0.00")){
                   }else{
                    productos.add(jtcomanda.getValueAt(fila, 2).toString()+"@"+jtcomanda.getValueAt(fila, 0).toString()+"@"+jtcomanda.getValueAt(fila, 3).toString()+"@"+jtcomanda.getValueAt(fila, 1).toString());               
           }       }
            TicketVenta ticketcliente=new TicketVenta();           
            ticketcliente.ImprimirDocumentoCliente(montototal,productos);
        }else{
          JOptionPane.showMessageDialog(null, "No hay productos en la comanda", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel) jtcomanda.getModel();  
          int fila=-1;
          fila=jtcomanda.getSelectedRow();
          if(fila!=-1){
              String prod=jtcomanda.getValueAt(jtcomanda.getSelectedRow(),1).toString();
              String idtempcomanda=jtcomanda.getValueAt(jtcomanda.getSelectedRow(),5).toString();
              String comentario="";
              if(jtcomanda.getValueAt(jtcomanda.getSelectedRow(),6)!=null){
                  comentario=jtcomanda.getValueAt(jtcomanda.getSelectedRow(),6).toString();
              }
              
               Frame f = JOptionPane.getFrameForComponent(this);
               Comentarios dialog = new Comentarios(f, true,idtempcomanda,prod,comentario);
               dialog.show();
          }else{
            JOptionPane.showMessageDialog(null, "Seleccionar un producto de la tabla.","Alerta",JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
                conex con=new conex();   
               try {                   
                   Statement st2 = con.getConnection().createStatement();
                   st2.executeUpdate("insert into rest_temp_venta (idrmesa,cantidad,descripcion,precio_venta,total,impreso,idrproducto,observacion) values ('"+idmesa+"','0','---------------------','0','0','1','0','')");                                                                                    
                   st2.close();
                   con.desconectar();                   
                   refreshinfo();
               } catch (SQLException ex) {                         
                  //JOptionPane.showMessageDialog(null, "Error al obtener los datos reg productos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }    
    }//GEN-LAST:event_jButton17ActionPerformed
public void vaciartabla(){
            DefaultTableModel modelo=(DefaultTableModel) jtcategorias.getModel();         
            for (int i = 0; i < jtcategorias.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    
    public void cargartablacateg(){    
        vaciartabla();
        DefaultTableModel modelo=(DefaultTableModel) jtcategorias.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from tc_categorias where estatus=1";
               //System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("Idcategoria"),rsR.getString("nombre")});                        
                   }
                  
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: de categorias"+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jccantidad;
    private javax.swing.JComboBox<String> jccliente;
    private javax.swing.JComboBox<String> jcmesero;
    private static javax.swing.JLabel jlmonto;
    private javax.swing.JTable jtcategorias;
    private static javax.swing.JTable jtcomanda;
    private javax.swing.JTable jtprod;
    private static javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtmesa;
    private javax.swing.JTextField txtota;
    // End of variables declaration//GEN-END:variables

public void cargartablacliente(){                    
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select idcliente,nombre_completo from tc_clientes";
        jccliente.addItem("");                        
               //System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            jccliente.addItem(rsR.getString("nombre_completo")+"-"+rsR.getString("idcliente"));                        
                   }                   
                   rsR.close(); 
                   st.close();
                   con.desconectar();
                   
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }   


public void cargartablamesero(){                    
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from tc_usuarios where estatus=1";
               //System.out.println(""+myQuery);
                jcmesero.addItem("");         
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            jcmesero.addItem(rsR.getString("nombre")+"-"+rsR.getString("idusuario"));                        
                   }                   
                   rsR.close(); 
                   st.close();
                   con.desconectar();
                   
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }   



public void vaciartablaprod(){
            DefaultTableModel modelo=(DefaultTableModel) jtprod.getModel();         
            for (int i = 0; i < jtprod.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    public void cargarproductos(String idcategoria){    
        vaciartablaprod();
        
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select count(nombre_producto) as total from tc_productos where estatus=1 and idrcategoria="+idcategoria;
               System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   int totalprod=0;
                   while(rsR.next()) { 
                    totalprod=rsR.getInt("total");
                   }
                   int filas=totalprod/3;
                   int residuo= totalprod%3;
                   if(residuo>0){
                   filas++;
                   }
                   
                   myQuery = "select * from tc_productos where estatus=1 and idrcategoria="+idcategoria;
                   rsR = st.executeQuery(myQuery);
                   int i=0;
                   String[] lbactivo=new String[4];
                   int contfila=1;
                   while(rsR.next()) {                                                 
                       
                       
                            DefaultTableModel modelo=(DefaultTableModel) jtprod.getModel();   
                            lbactivo[i]=rsR.getString("idproducto")+"-"+rsR.getString("nombre_producto");
                            i++;
                            if(i==3){
                                 contfila++;
                                 i=0;
                                 modelo.addRow(new Object[]{lbactivo[0],lbactivo[1],lbactivo[2]});                                               
                            }
                            System.out.println(contfila+"=="+filas+" && "+residuo+"==2 && "+i+"==2");
                            if(contfila==filas && residuo==2 && i==2){
                                System.out.println("residuo 2");
                                modelo.addRow(new Object[]{lbactivo[0],lbactivo[1],""});      
                            }
                            System.out.println(contfila+"=="+filas+" && "+residuo+"==1 && "+i+"==1");
                            if(contfila==filas && residuo==1 && i==1){
                                System.out.println("residuo 1");
                                modelo.addRow(new Object[]{lbactivo[0],"",""});      
                            }
                            
                            
                       
                   }                  
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }    
              
              
    }
   

 public void cargarprodventa(String prod){
    DefaultTableModel modelo=(DefaultTableModel) jtcomanda.getModel(); 
    String cantidad=jccantidad.getSelectedItem().toString();
    String[] temp=prod.split("-");
    String idprod=temp[0];
          conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from tc_productos where idproducto="+idprod;
               //System.out.println(""+myQuery);                    
               try {
                   Statement st = con.getConnection().createStatement();
                   Statement st2 = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {     
                           double totl=Float.parseFloat(cantidad)*rsR.getFloat("precio_venta");
                           funciones redondeo=new funciones();
                           totl=redondeo.redondearDecimales(totl,2);
                           st2.executeUpdate("insert into rest_temp_venta (idrmesa,cantidad,descripcion,precio_venta,total,impreso,idrproducto,observacion) values ('"+idmesa+"','"+cantidad+"','"+rsR.getString("nombre_producto")+"','"+rsR.getString("precio_venta")+"','"+totl+"','1','"+rsR.getString("idproducto")+"','')");
                           System.out.println("inserta temp");
                           //modelo.addRow(new Object[]{cantidad,rsR.getString("nombre_producto"),rsR.getString("precio_venta"),totl+""});                        
                           
                   }                   
                   rsR.close(); 
                   st.close();
                   con.desconectar();                   
               } catch (SQLException ex) {                         
                  //JOptionPane.showMessageDialog(null, "Error al obtener los datos reg productos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }    
     
     
 }   

 public static void refreshinfo(){
       DefaultTableModel modelo=(DefaultTableModel) jtcomanda.getModel(); 
       for (int i = 0; i < jtcomanda.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
       } 
       
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select * from rest_temp_venta where idrmesa="+idmesa+" order by Idtemp asc";
               //System.out.println(""+myQuery);                    
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {     
                           modelo.addRow(new Object[]{rsR.getString("cantidad"),rsR.getString("descripcion"),rsR.getString("precio_venta"),rsR.getString("total"),rsR.getString("idrproducto"),rsR.getString("Idtemp"),rsR.getString("observacion")});                                                   
                   }                   
                   rsR.close(); 
                   st.close();
                   con.desconectar();                   
               } catch (SQLException ex) {                         
                  JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }    
     
     
     
     
       double total=0,cantidad=0,precio=0,grantotal=0;
       int noarticulos=0;
       funciones redondear=new funciones();
       for(int fila=0; fila<jtcomanda.getRowCount(); fila++){               
                //cantidad=Float.parseFloat(jtcomanda.getValueAt(fila, 0).toString());    
                grantotal=grantotal+Float.parseFloat(jtcomanda.getValueAt(fila, 3).toString());    
                //total=cantidad*precio;
                //total=redondear.redondearDecimales(total, 2); 
                //grantotal=grantotal+total;
                noarticulos++;
       }
       //DecimalFormat df = new DecimalFormat("0.00"); 
       //jlmonto.setText("$ "+df.format(total_valor)+"");    
       
       grantotal=redondear.redondearDecimales(grantotal, 2);  
       jlmonto.setText("$ "+grantotal+""); 
       double iva=obteniva();
       double subtotal=grantotal;
        subtotal=subtotal+(subtotal*iva);
       lbltotal.setText("$ "+subtotal+""); 
 }


public static void statusmesa(String status){
    
     conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "update rest_mesas set estatus='"+status+"' where IdMesa="+idmesa;
               //System.out.println(""+myQuery);                    
               try {
                   Statement st = con.getConnection().createStatement();
                   st.executeUpdate(myQuery);                   
                   st.close();
                   con.desconectar();                   
               } catch (SQLException ex) {                         
                  JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }   
    
}


public static String obtenidcliente(String id){
        String ids=id;
        String[] temp=ids.split("-");
        for(int i=1;i<2;i++){
            ids=temp[i];
        }
    return ids;
    }


    public static double obteniva(){
    double iva=0.0;    
    conex cn = new conex();    
    String sql="SELECT parametro from to_parametros where clave='IVA'";
    System.out.println(sql);
    PreparedStatement pstm100;
    try {
            pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
            ResultSet rs100 = (ResultSet) pstm100.executeQuery();
        while (rs100.next()) {

            iva=rs100.getDouble("parametro");	    		    			   
            }
        rs100.close();
        pstm100.close();
        cn.desconectar();
    } catch (SQLException e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
    }
    iva=iva/100;
    return iva;
    }
    
  public static void cerrarmesa(){

      
        statusmesa("LIBRE");
        //REALIZAR EL COBRO
        
        
                conex con=new conex();   
                 ResultSet rsR = null;        
                 String myQuery = "delete from rest_temp_venta where idrmesa="+idmesa;               
               try {
                  Statement st = con.getConnection().createStatement();
                  st.executeUpdate(myQuery);
                  st.close();
                  con.desconectar();
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al vaciar datos de la venta: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }  
      refreshinfo();
  }  
    
}
