/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Restaurant;

import jdialog.*;

import Utilerias.funciones;
import com.mysql.jdbc.PreparedStatement;
import conexion.conex;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jinternalPanel.Ventas;

/**
 *
 * @author desarrollo8
 */
public class Cobrar_ventaRestaurant extends javax.swing.JDialog {
private TableRowSorter<TableModel> sorter;
ArrayList productosok;
double montofinal;
double subtotal;
double ieps;
String idclientefac="";
String idmesa="",meseros="";
    /**
     * Creates new form Cobrar_venta
     */
    public Cobrar_ventaRestaurant(java.awt.Frame parent, boolean modal,double costo,ArrayList productos,double subtotales,String idclientefactura, double iep,String mesa,String mesero) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);                
        ieps=iep;
        subtotal=subtotales;
        montofinal=costo;
        txtcobro.setText(montofinal+"");
        idclientefac=idclientefactura;
        idmesa=mesa;
        
        productosok=productos;
        jpefectivo.setVisible(true);
        jptarjeta.setVisible(false);
        jppuntos.setVisible(false);
        jpmixto.setVisible(false);
        jpcredito.setVisible(false);
        txtefectivo.requestFocus();
        meseros=mesero;
        //lectura del arraylist con todos los productos
        //for(int x=0;x<productosok.size();x++) {
            //System.out.println(productos.get(x));
        //}
        cargartablacliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrefectivo = new javax.swing.JRadioButton("EFECTIVO",true);
        jrtarjeta = new javax.swing.JRadioButton();
        jrpuntos = new javax.swing.JRadioButton();
        jrmixto = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtdescuento = new javax.swing.JTextField();
        jcdescuento = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jcformadescuento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcobro = new java.awt.Label();
        label1 = new java.awt.Label();
        jpefectivo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtefectivo = new javax.swing.JTextField();
        txtcambio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jptarjeta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtreferencia = new javax.swing.JTextField();
        jppuntos = new javax.swing.JPanel();
        jpmixto = new javax.swing.JPanel();
        txtefectivomix = new javax.swing.JTextField();
        txtcreditomix = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtreferenciamix = new javax.swing.JTextField();
        jrcredito = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jpcredito = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtclientes = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cobrar Venta");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 242, 242));

        jbgroup.add(jrefectivo);
        jrefectivo.setText("EFECTIVO");
        jrefectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrefectivoActionPerformed(evt);
            }
        });

        jrtarjeta.setVisible(true);
        jbgroup.add(jrtarjeta);
        jrtarjeta.setText("TARJETA");
        jrtarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrtarjetaActionPerformed(evt);
            }
        });

        jrpuntos.setVisible(false);
        jbgroup.add(jrpuntos);
        jrpuntos.setText("PUNTOS");
        jrpuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrpuntosActionPerformed(evt);
            }
        });

        jrmixto.setVisible(true);
        jbgroup.add(jrmixto);
        jrmixto.setText("MIXTO");
        jrmixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrmixtoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(244, 243, 243));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton1.setText("Cobrar con ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/palomita.png"))); // NOI18N
        jButton2.setVisible(false);
        jButton2.setText("Cobrar sin ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtdescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtdescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescuentoKeyTyped(evt);
            }
        });

        jcdescuento.setText("Descuento");
        jcdescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdescuentoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("%");

        jcformadescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PORCENTAJE", "EFECTIVO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcdescuento)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcformadescuento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdescuento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jcformadescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcdescuento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/efectivo.png"))); // NOI18N

        jLabel2.setVisible(true);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjeta.png"))); // NOI18N

        jLabel3.setVisible(false);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monedero.png"))); // NOI18N

        jLabel4.setVisible(true);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pagomixto.png"))); // NOI18N

        txtcobro.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txtcobro.setForeground(new java.awt.Color(0, 51, 102));
        txtcobro.setText("0.00");

        label1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 51, 102));
        label1.setText("$");

        jpefectivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Efectivo");

        txtefectivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtefectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtefectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtefectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtefectivoKeyTyped(evt);
            }
        });

        txtcambio.setBackground(new java.awt.Color(204, 204, 255));
        txtcambio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtcambio.setForeground(new java.awt.Color(51, 204, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Cambio");

        javax.swing.GroupLayout jpefectivoLayout = new javax.swing.GroupLayout(jpefectivo);
        jpefectivo.setLayout(jpefectivoLayout);
        jpefectivoLayout.setHorizontalGroup(
            jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpefectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcambio)
                    .addComponent(txtefectivo))
                .addGap(18, 18, 18))
        );
        jpefectivoLayout.setVerticalGroup(
            jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpefectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtefectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpefectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jptarjeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Referencia");

        txtreferencia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtreferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtreferenciaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jptarjetaLayout = new javax.swing.GroupLayout(jptarjeta);
        jptarjeta.setLayout(jptarjetaLayout);
        jptarjetaLayout.setHorizontalGroup(
            jptarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jptarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jptarjetaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtreferencia))
                .addContainerGap())
        );
        jptarjetaLayout.setVerticalGroup(
            jptarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jppuntosLayout = new javax.swing.GroupLayout(jppuntos);
        jppuntos.setLayout(jppuntosLayout);
        jppuntosLayout.setHorizontalGroup(
            jppuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jppuntosLayout.setVerticalGroup(
            jppuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jpmixto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtefectivomix.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtefectivomix.setForeground(new java.awt.Color(0, 51, 204));
        txtefectivomix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtefectivomixKeyTyped(evt);
            }
        });

        txtcreditomix.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtcreditomix.setForeground(new java.awt.Color(0, 51, 204));
        txtcreditomix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcreditomixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcreditomixKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("EFECTIVO $");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("TARJETA $");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("REFERENCIA");

        txtreferenciamix.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtreferenciamix.setForeground(new java.awt.Color(0, 51, 204));
        txtreferenciamix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtreferenciamixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtreferenciamixKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpmixtoLayout = new javax.swing.GroupLayout(jpmixto);
        jpmixto.setLayout(jpmixtoLayout);
        jpmixtoLayout.setHorizontalGroup(
            jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmixtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtefectivomix)
                    .addComponent(txtcreditomix)
                    .addComponent(txtreferenciamix))
                .addGap(93, 93, 93))
        );
        jpmixtoLayout.setVerticalGroup(
            jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmixtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtefectivomix)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtreferenciamix)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpmixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcreditomix)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jrcredito.setVisible(true);
        jbgroup.add(jrcredito);
        jrcredito.setText("CREDITO");
        jrcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrcreditoActionPerformed(evt);
            }
        });

        jLabel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N

        jpcredito.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtclientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtclientes);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Cliente");

        txtcliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclienteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpcreditoLayout = new javax.swing.GroupLayout(jpcredito);
        jpcredito.setLayout(jpcreditoLayout);
        jpcreditoLayout.setHorizontalGroup(
            jpcreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jpcreditoLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcliente))
        );
        jpcreditoLayout.setVerticalGroup(
            jpcreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpcreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrefectivo))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrtarjeta)
                                .addGap(82, 82, 82)
                                .addComponent(jrcredito))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrpuntos)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrmixto)))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jptarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpefectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jppuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpmixto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpcredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcobro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcobro, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrmixto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrtarjeta)
                                    .addComponent(jrcredito)
                                    .addComponent(jrefectivo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrpuntos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jppuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpmixto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jpefectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jptarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpcredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jrefectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrefectivoActionPerformed
        // TODO add your handling code here:
        jpefectivo.setVisible(true);
        jptarjeta.setVisible(false);        
        jppuntos.setVisible(false);
        jpmixto.setVisible(false);
        jpcredito.setVisible(false);
        txtefectivo.requestFocus();
        
    }//GEN-LAST:event_jrefectivoActionPerformed

    private void jrtarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrtarjetaActionPerformed
        // TODO add your handling code here:
        
        jpefectivo.setVisible(false);
        jptarjeta.setVisible(true);
        jppuntos.setVisible(false);
        jpmixto.setVisible(false);
        jpcredito.setVisible(false);
        txtreferencia.requestFocus();
    }//GEN-LAST:event_jrtarjetaActionPerformed

    private void jrpuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrpuntosActionPerformed
        // TODO add your handling code here:
        jpefectivo.setVisible(false);
        jptarjeta.setVisible(false);
        jppuntos.setVisible(true);
        jpmixto.setVisible(false);
        jpcredito.setVisible(false);
        
    }//GEN-LAST:event_jrpuntosActionPerformed

    private void jrmixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrmixtoActionPerformed
        // TODO add your handling code here:
        jpefectivo.setVisible(false);
        jptarjeta.setVisible(false);
        jppuntos.setVisible(false);
        jpmixto.setVisible(true);
        jpcredito.setVisible(false);
        txtefectivomix.requestFocus();
    }//GEN-LAST:event_jrmixtoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double descu=0;
        boolean validadescuento=true;
        String formadescuento=jcformadescuento.getSelectedItem().toString(); //porecntaje o efectivo
        if(jcdescuento.isSelected()){
            String descuento=txtdescuento.getText().trim().toString();
            if(descuento.equals("")){
                descuento="0";
            }
            descu=Float.parseFloat(descuento);
            
            String validaclave=contra("Introdusca la contraseña para aplicar descuento","Descuento");
            if(validaclave.equals("NOPROCESAR")){
                JOptionPane.showMessageDialog(null, "La contraseña no es correcta vuelva a intentarlo.", "Alerta", JOptionPane.ERROR_MESSAGE);
                validadescuento=false;
            }
        }
        
        if(validadescuento==true){
            if(jrefectivo.isSelected()==true)
            {
                String montoefec=txtefectivo.getText().trim();
                if(txtefectivo.getText().trim().equals("")){
                    montoefec="0";
                }
                float cobrarmonto=Float.parseFloat(montoefec);
                System.out.println("cobrar:"+cobrarmonto);
                if(montofinal<=cobrarmonto){   
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrar(montofinal,cobrarmonto,"","EFECTIVO",productosok,"SINIMPRIMIR",descu,"",formadescuento,idclientefac,ieps,idmesa,meseros);                
                    if(exito==true){
                        Ventas.vaciartabla();
                        Ventas.cargar_informacion();
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El monto ingresado no alcanza para cubrir el pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }

            }else if(jrtarjeta.isSelected()==true)
            {         
                String referencia=txtreferencia.getText().trim();            
                if(!referencia.equals("")){   
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrar(montofinal,0,referencia,"TARJETA",productosok,"SINIMPRIMIR",descu,"",formadescuento,idclientefac,ieps,idmesa,meseros);                
                    if(exito==true){
                        Ventas.vaciartabla();
                        Ventas.cargar_informacion();
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No ha ingresado el numero de referencia del pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }

            }else if(jrpuntos.isSelected()==true)
            {
             System.out.print("Seleccionó opción 1");
            }else if(jrmixto.isSelected()==true)
            {
             System.out.print("Seleccionó opción 2");
            }else{
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna forma de pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtefectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivoKeyTyped
        // TODO add your handling code here:
        if(txtefectivo.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
               evt.consume(); // ignorar el evento de teclado
            }
        }
        
         
    }//GEN-LAST:event_txtefectivoKeyTyped

    private void txtefectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivoKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){        
            cobrarconticket();
        }
    }//GEN-LAST:event_txtefectivoKeyPressed

    private void txtefectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivoKeyReleased
        // TODO add your handling code here:
        
        String efec=txtefectivo.getText().trim().toString();
        if(efec.equals("")){
            efec="0";
	}
        float efectivo=Float.parseFloat(efec);
        String efe2=txtcobro.getText();
        String au=efe2+"";						
        float aa1 = Float.parseFloat(au);																		
        System.out.println("val: "+aa1);							
        double cambios=efectivo-aa1;
        funciones redondeo=new funciones();
        //cambios=Math.rint((cambios*1000)/1000);//redondea los numeros
        cambios=redondeo.redondearDecimales(cambios, 2);//redondea los numeros
        
        System.out.println("CAMBIO: "+cambios);
        txtcambio.setText(cambios+"");
        System.out.println("hola"+efec);
    }//GEN-LAST:event_txtefectivoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       cobrarconticket();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescuentoKeyTyped
        // TODO add your handling code here:
        
        if(txtdescuento.getText().trim().length()>=4){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
               evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtdescuentoKeyTyped

    private void txtdescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescuentoKeyReleased
        // TODO add your handling code here:
        String tipodescuento=jcformadescuento.getSelectedItem().toString();
        if(jcdescuento.isSelected()){
            String descuento=txtdescuento.getText().trim().toString();
            if(descuento.equals("")){
                descuento="0";
            }            
            double montoconiva=montofinal;
            montoconiva=(montoconiva*1000)/1000;//redondea los numeros
            
            double descu=Float.parseFloat(descuento);
            String efe2=montoconiva+"";
            String au=efe2+"";						
            double cobrar = Float.parseFloat(au);

            double resultdescuento = (descu * cobrar)/100; 
            if(tipodescuento.equals("EFECTIVO")){
                resultdescuento=descu;
            }
            
            System.out.println("resultado: "+resultdescuento);

            double cambios=cobrar-resultdescuento;
            
            cambios=Math.rint((cambios*1000)/1000);//redondea los numeros
            
            txtcobro.setText(cambios+"");        
            txtefectivo.setText("");
        }
        
        
    }//GEN-LAST:event_txtdescuentoKeyReleased

    private void jcdescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdescuentoActionPerformed
        // TODO add your handling code here:
        txtdescuento.setText("");
    }//GEN-LAST:event_jcdescuentoActionPerformed

    private void txtreferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreferenciaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){        
            cobrarconticket();
        }
    }//GEN-LAST:event_txtreferenciaKeyPressed

    private void jrcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrcreditoActionPerformed
        // TODO add your handling code here:
        jpcredito.setVisible(true);
        jpefectivo.setVisible(false);
        jptarjeta.setVisible(false);
        jppuntos.setVisible(false);
        jpmixto.setVisible(false);
        txtcliente.requestFocus();
        
    }//GEN-LAST:event_jrcreditoActionPerformed

    private void txtclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyPressed
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtclienteKeyPressed

    private void txtefectivomixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivomixKeyTyped
        // TODO add your handling code here:
        if(txtefectivomix.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
               evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtefectivomixKeyTyped

    private void txtcreditomixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcreditomixKeyTyped
        // TODO add your handling code here:
        if(txtcreditomix.getText().trim().length()>=9){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }else{
            if (((evt.getKeyChar() < '0') || (evt.getKeyChar() > '9')) && (evt.getKeyChar() != '.')){
               evt.consume(); // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_txtcreditomixKeyTyped

    private void txtcreditomixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcreditomixKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){        
            cobrarconticket();
        }
    }//GEN-LAST:event_txtcreditomixKeyPressed

    private void txtreferenciamixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreferenciamixKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreferenciamixKeyPressed

    private void txtreferenciamixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreferenciamixKeyTyped
        // TODO add your handling code here:
        if(txtreferenciamix.getText().trim().length()>=40){
            //JOptionPane.showMessageDialog(null, "Solo acepta 15 caracteres", "Alerta", JOptionPane.ERROR_MESSAGE);
            evt.consume(); // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtreferenciamixKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar_ventaRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar_ventaRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar_ventaRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar_ventaRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList productos=new ArrayList();
                productos.add("1234");
                Cobrar_ventaRestaurant dialog = new Cobrar_ventaRestaurant(new javax.swing.JFrame(), true,6,productos,0,"",0,"0","0");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
public String contra(String mensaje,String titulo){
    String password = "";
    JPasswordField passwordField = new JPasswordField();
    Object[] obj = {mensaje+":\n\n", passwordField};
    Object stringArray[] = {"OK","Cancel"};
    if (JOptionPane.showOptionDialog(null, obj, titulo,JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
    null, stringArray, obj) == JOptionPane.YES_OPTION)
    {
    password = new String(passwordField.getPassword());
    }
    System.out.println("contra: "+password);
    
    
        conex cn = new conex();
	String sql="SELECT parametro from to_parametros where clave='CLAVEADMIN'";
	String clave="";
	PreparedStatement pstm100;
	try {
		pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
		ResultSet rs100 = (ResultSet) pstm100.executeQuery();
                while (rs100.next()) {
                    clave=rs100.getString("parametro");
	    	
		}
	    rs100.close();
            pstm100.close();
            cn.desconectar();
	} catch (SQLException e2) {
		// TODO Auto-generated catch block
		e2.printStackTrace();
	}
    
    
    String valida="NOPROCESAR";
    if(password.equals(clave)){
        valida="PROCESARVENTA";
    }
    System.out.println("contra: "+valida);
    return valida;    
}

public void cobrarconticket(){


     boolean validadescuento=true;
        double descu=0;
        String formadescuento=jcformadescuento.getSelectedItem().toString(); //porecntaje o efectivo
        if(jcdescuento.isSelected()){
            String descuento=txtdescuento.getText().trim().toString();
            if(descuento.equals("")){
                descuento="0";
            }
            descu=Float.parseFloat(descuento);
            String validaclave=contra("Introdusca la contraseña para aplicar descuento","Descuento");
            if(validaclave.equals("NOPROCESAR")){
                JOptionPane.showMessageDialog(null, "La contraseña no es correcta vuelva a intentarlo.", "Alerta", JOptionPane.ERROR_MESSAGE);
                validadescuento=false;
            }
        }
        if(validadescuento==true){
            if(jrcredito.isSelected()==true){
                int fila=-1;
                fila=jtclientes.getSelectedRow();
                if(fila!=-1){
                    String idcliente=jtclientes.getValueAt(jtclientes.getSelectedRow(),0).toString();            
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrarcreditocliente(subtotal,0,"","CREDITO",productosok,"MANDAIMPRIMIR",descu,idcliente,idclientefac,ieps);                
                    if(exito==true){
                        AddProductos.cerrarmesa();
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un Cliente.","Alerta",JOptionPane.ERROR_MESSAGE);
                }
            }else if(jrmixto.isSelected()==true)
            {
                String referencia=txtreferenciamix.getText().trim();
                float cobrarefectivo=0;                
                float cobrartarjeta=0;
                float cobrarmonto=0;
                boolean validaformato=true;
                try{
                cobrarefectivo=Float.parseFloat(txtefectivomix.getText().trim());
                cobrartarjeta=Float.parseFloat(txtcreditomix.getText().trim());                
                cobrarmonto=cobrarefectivo+cobrartarjeta;
                }catch(NumberFormatException ex){
                    validaformato=false;
                    //JOptionPane.showMessageDialog(null, "El monto es invalido favor de verificar.", "Alerta", JOptionPane.ERROR_MESSAGE);        
                }
                
                float nuevomonto=Float.parseFloat(txtcobro.getText().trim());
                System.out.println("cobrar:"+cobrarmonto);
                if(txtefectivomix.getText().trim().equals("")){
                    txtefectivomix.requestFocus();
                    JOptionPane.showMessageDialog(null, "Debe ingresar el monto en efectivo.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }else if(txtcreditomix.getText().trim().equals("")){
                    txtcreditomix.requestFocus();
                    JOptionPane.showMessageDialog(null, "Debe ingresar el monto de la tarjeta.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }else if(validaformato==false){
                    JOptionPane.showMessageDialog(null, "Formato de montos no valido favor de revisar.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }else if(referencia.equals("")){
                    txtreferenciamix.requestFocus();
                    JOptionPane.showMessageDialog(null, "Debe ingresar la referencia del cobro.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }else if(nuevomonto>cobrarmonto){   
                    txtefectivomix.requestFocus();
                    JOptionPane.showMessageDialog(null, "El monto ingresado no alcanza para cubrir el pago.", "Alerta", JOptionPane.ERROR_MESSAGE);                    
                }else{
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrar(subtotal,cobrarefectivo,cobrartarjeta+"","MIXTO",productosok,"MANDAIMPRIMIR",descu,referencia,formadescuento,idclientefac,ieps,idmesa,meseros);                
                    if(exito==true){
                       AddProductos.cerrarmesa();
                        dispose();
                    }
                }

            }else if(jrefectivo.isSelected()==true)
            {

                float cobrarmonto=Float.parseFloat(txtefectivo.getText().trim());
                float nuevomonto=Float.parseFloat(txtcobro.getText().trim());
                System.out.println("cobrar:"+cobrarmonto);
                if(nuevomonto<=cobrarmonto){   
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrar(subtotal,cobrarmonto,"","EFECTIVO",productosok,"MANDAIMPRIMIR",descu,"",formadescuento,idclientefac,ieps,idmesa,meseros);                
                    if(exito==true){
                        AddProductos.cerrarmesa();
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El monto ingresado no alcanza para cubrir el pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }

            }else if(jrtarjeta.isSelected()==true)
            {         
                String referencia=txtreferencia.getText().trim();            
                if(!referencia.equals("")){   
                    cobrar_ventaFinalRes cobro=new cobrar_ventaFinalRes();
                    boolean exito=cobro.cobrar(subtotal,0,referencia,"TARJETA",productosok,"MANDAIMPRIMIR",descu,"",formadescuento,idclientefac,ieps,idmesa,meseros);                
                    if(exito==true){
                        AddProductos.cerrarmesa();
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No ha ingresado el numero de referencia del pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
                }

            }else if(jrpuntos.isSelected()==true)
            {
             System.out.print("Seleccionó opción 1");
            }else if(jrmixto.isSelected()==true)
            {
             System.out.print("Seleccionó opción 2");
            }else{
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna forma de pago.", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }

}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jbgroup;
    private javax.swing.JCheckBox jcdescuento;
    private javax.swing.JComboBox<String> jcformadescuento;
    private javax.swing.JPanel jpcredito;
    private javax.swing.JPanel jpefectivo;
    private javax.swing.JPanel jpmixto;
    private javax.swing.JPanel jppuntos;
    private javax.swing.JPanel jptarjeta;
    private javax.swing.JRadioButton jrcredito;
    private javax.swing.JRadioButton jrefectivo;
    private javax.swing.JRadioButton jrmixto;
    private javax.swing.JRadioButton jrpuntos;
    private javax.swing.JRadioButton jrtarjeta;
    private javax.swing.JTable jtclientes;
    private java.awt.Label label1;
    private javax.swing.JTextField txtcambio;
    private javax.swing.JTextField txtcliente;
    private java.awt.Label txtcobro;
    private javax.swing.JTextField txtcreditomix;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtefectivo;
    private javax.swing.JTextField txtefectivomix;
    private javax.swing.JTextField txtreferencia;
    private javax.swing.JTextField txtreferenciamix;
    // End of variables declaration//GEN-END:variables

   

public double obteniva(){
    double iva=0.0;    
    conex cn = new conex();    
    String sql="SELECT parametro from to_parametros where clave='IVA'";
    System.out.println(sql);
    PreparedStatement pstm100;
    try {
            pstm100 = (PreparedStatement) cn.getConnection().prepareStatement(sql);
            ResultSet rs100 = (ResultSet) pstm100.executeQuery();
        while (rs100.next()) {

            iva=rs100.getDouble("parametro");	    		    			   
            }
        rs100.close();
        pstm100.close();
        cn.desconectar();
    } catch (SQLException e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
    }
    iva=iva/100;
    return iva;
 }


public void vaciartabla(){
            DefaultTableModel modelo=(DefaultTableModel) jtclientes.getModel();         
            for (int i = 0; i < jtclientes.getRowCount(); i++) {
                modelo.removeRow(i);
                i-=1;
            }    
    }
    private void filtrar() {
        
         RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("(?i)"+txtcliente.getText(),1);
        }catch (java.util.regex.PatternSyntaxException e) {
        }
        sorter.setRowFilter(rf);
    }
public void cargartablacliente(){    
        vaciartabla();
        DefaultTableModel modelo=(DefaultTableModel) jtclientes.getModel();  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select idcliente,nombre_completo from tc_clientes";
               //System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) {                                                
                            modelo.addRow(new Object[]{rsR.getString("idcliente"),rsR.getString("nombre_completo")});                        
                   }
                   sorter = new TableRowSorter<TableModel>(modelo);
                   jtclientes.setRowSorter(sorter);
                   rsR.close(); 
                   st.close();
                   con.desconectar();
                   jtclientes.getColumnModel().getColumn(0).setMaxWidth(0);
                   jtclientes.getColumnModel().getColumn(0).setMinWidth(0);
                   jtclientes.getColumnModel().getColumn(0).setPreferredWidth(0);
                   jtclientes.getColumnModel().getColumn(0).setWidth(0);
               } catch (SQLException ex) {       
                  
                   JOptionPane.showMessageDialog(null, "Error al obtener los datos: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
               
              
    }    


}
