/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puntoventa;

import ClasesDAO.accesoSistema;
import Fidelizaciones.Catfideliza;
import ModuloVeterinaria.NotificacionesDiarias;
import NotaCredito.ConsultarNotasCredito;
import NotaCredito.NotaCredito;
import PosVenta.Pos_Ventas;
import Restaurant.Comandera;
import TraspasoProductos.RecepciondeProductos;
import TraspasoProductos.Traspasos;
import Utilerias.LectorXML;
import administracionFacturas.FacturarTicket;
import administracionFacturas.FacturarTicketMasivo;
import administracionFacturas.FacturasGeneradas;
import conexion.conex;
import farmacias.CatalogoLotes;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import jdialog.Calendario;
import jdialog.CambiarContra;
import jdialog.CambiarUsuario;
import jdialog.ConsultarCotizaciones;
import jdialog.ConsultarPrecio;
import jdialog.RespaldoBD;
import jinternalPanel.Categorias;
import jinternalPanel.Cierre_caja;
import jinternalPanel.Clientes;
import jinternalPanel.Configuracion;
import jinternalPanel.CorteCajas;
import jinternalPanel.Cotizacion;
import jinternalPanel.Inventario;
import jinternalPanel.PreCierre_caja;
import jinternalPanel.Productos;
import jinternalPanel.ProductosVendidosCosto;
import jinternalPanel.Productos_mas_Vendidos;
import jinternalPanel.Proveedores.CatProveedores;
import jinternalPanel.Proveedores.Proveedores;
import jinternalPanel.Proveedores.ReporteCompras;
import jinternalPanel.Proveedores.ReporteDetallado;
import jinternalPanel.ReporteGeneral;
import jinternalPanel.Usuarios;
import jinternalPanel.Ventas;
import jinternalPanel.EsteticaRep;
import jinternalPanel.RestMesas;
import plasticos.Inicial;
import serviciotecnico.ServicioTec;

/**
 *
 * @author desarrollo8
 */
public class PantallaPrincipal extends javax.swing.JFrame implements KeyListener {
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        String rutaicon="/images/icono.png";        
        String ruta=rutaicon;      
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ruta));
        setIconImage(icon);
        validamulticajas();
        String ruta_logo=new File ("").getAbsolutePath ()+"/imagenes_configurables/logo_sistema.jpg";
        File fichero = new File(ruta_logo);
        if (fichero.exists()){
            jllogo.setIcon(new ImageIcon(ruta_logo));
        }
        
        if(accesoSistema.ventas.equals("1")){    
            Ventas v1=new Ventas();        
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jllogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jLabel2.setText("jLabel2");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Venta");

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        jllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_grande.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Le atiende:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Administrador de la Tienda");
        jLabel4.setText(accesoSistema.nombreuser);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(escritorio)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(579, 29));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito.png"))); // NOI18N
        jMenu1.setText("Ventas");
        if(accesoSistema.ventas.equals("0")){
            jMenu1.setVisible(false);
        }
        jMenu1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historico.png"))); // NOI18N
        jMenu2.setText("Catálogos");
        if(accesoSistema.catprod.equals("1") || accesoSistema.catcateg.equals("1") || accesoSistema.catcliente.equals("1") || accesoSistema.catusuario.equals("1")){
            jMenu2.setVisible(true);
        }else{
            jMenu2.setVisible(false);
        }
        jMenu2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jMenuItem1.setText("Clientes");
        if(accesoSistema.catcliente.equals("0")){
            jMenuItem1.setVisible(false);
        }
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto.png"))); // NOI18N
        jMenuItem2.setText("Productos");
        if(accesoSistema.catprod.equals("0")){
            jMenuItem2.setVisible(false);
        }
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        if(accesoSistema.catusuario.equals("0")){
            jMenuItem3.setVisible(false);
        }
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        jMenuItem3.setText("Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rep.png"))); // NOI18N
        if(accesoSistema.catcateg.equals("0")){
            jMenuItem14.setVisible(false);
        }
        jMenuItem14.setText("Categorias");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte3.gif"))); // NOI18N
        jMenuItem13.setText("Fidelizaciones");
        if(accesoSistema.menufidelizaciones.equals("0")){
            jMenuItem13.setVisible(false);
        }
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultas.png"))); // NOI18N
        jMenu13.setText("Módulos");
        jMenu13.setVisible(true);
        jMenu13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte3.gif"))); // NOI18N
        jMenu11.setText("Traspasos");
        jMenu11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        if(accesoSistema.traspasos.equals("0")){
            jMenu11.setVisible(false);
        }

        jMenuItem23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seg.png"))); // NOI18N
        jMenuItem23.setText("Generar Traspaso");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto_bajo.png"))); // NOI18N
        jMenuItem24.setText("Recibir Traspaso");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem24);

        jMenu13.add(jMenu11);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedor.png"))); // NOI18N
        jMenu10.setText("Proveedores");
        if(accesoSistema.proveedores.equals("0")){
            jMenu10.setVisible(false);
        }
        jMenu10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/provedores.png"))); // NOI18N
        jMenuItem18.setText("Catálogo");
        if(!accesoSistema.privilegio.equals("ADMINISTRADOR")){
            jMenuItem18.setVisible(false);
        }
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuItem15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras.png"))); // NOI18N
        jMenuItem15.setText("Compras");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenuItem17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte3.gif"))); // NOI18N
        jMenuItem17.setText("Reportes");
        if(!accesoSistema.privilegio.equals("ADMINISTRADOR")){
            jMenuItem17.setVisible(false);
        }
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenuItem19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte2.png"))); // NOI18N
        jMenuItem19.setText("Reporte Detallado");
        if(!accesoSistema.privilegio.equals("ADMINISTRADOR")){
            jMenuItem19.setVisible(false);
        }
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem19);

        jMenu13.add(jMenu10);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        jMenu12.setText("Facturación");
        jMenu12.setVisible(true);
        jMenu12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        if(accesoSistema.menufacturacion.equals("0")){
            jMenu12.setVisible(false);
        }

        jMenuItem26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem26.setText("Facturar Ticket");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem26);

        jMenuItem27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem27.setText("Facturar Publico Gral");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem27);

        jMenuItem28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem28.setText("Facturas Emitidas");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem28);

        jMenu13.add(jMenu12);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historico.png"))); // NOI18N
        jMenu14.setText("Nota de Crédito");
        if(accesoSistema.menunotacredito.equals("0")){
            jMenu14.setVisible(false);
        }
        jMenu14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem30.setText("Generar");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem30);

        jMenuItem31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem31.setText("Consultar");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem31);

        jMenu13.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurant.png"))); // NOI18N
        jMenu15.setText("Restaurant");
        if(accesoSistema.menurestaurant.equals("0")){
            jMenu15.setVisible(false);
        }
        jMenu15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem33.setText("Comandas");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem33);

        jMenuItem32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem32.setText("Catálogo Mesas");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem32);

        jMenu13.add(jMenu15);

        jMenuItem34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuItem34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jMenuItem34.setText("Servicio Técnico");
        if(accesoSistema.menuserviciotecnico.equals("0")){
            jMenuItem34.setVisible(false);
        }
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem34);

        jMenuItem36.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuItem36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cortecaja.png"))); // NOI18N
        jMenuItem36.setVisible(false);
        jMenuItem36.setText("Pre Venta");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem36);

        jMenuItem37.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuItem37.setText("Cargar XML");
        jMenuItem37.setVisible(true);
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem37);

        jMenuItem39.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuItem39.setVisible(true);
        jMenuItem39.setText("Venta Touch");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem39);

        jMenuItem40.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenuItem40.setText("Farmacia Lotes");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem40);
        if(accesoSistema.menufarmacia.equals("0")){
            jMenuItem40.setVisible(false);
        }

        jMenuBar1.add(jMenu13);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        jMenu3.setText("Inventario");
        if(accesoSistema.inventarios.equals("0")){
            jMenu3.setVisible(false);
        }
        jMenu3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        if(accesoSistema.licencia.equals("DEMO")){
            jMenu4.setVisible(false);
        }
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Configuracion.png"))); // NOI18N
        jMenu4.setText("Configuración");
        if(!accesoSistema.privilegio.equals("ADMINISTRADOR")){
            jMenu4.setVisible(false);
        }
        jMenu4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        jMenu5.setText("Cierre Caja");
        jMenu5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        if(accesoSistema.licencia.equals("DEMO")){
            jMenu5.setVisible(false);
        }
        if(accesoSistema.cierrecaja.equals("0")){
            jMenu5.setVisible(false);
        }
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        jMenuItem11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        jMenuItem11.setText("Corte");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cortecaja.png"))); // NOI18N
        jMenuItem12.setText("Pre Corte");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultas.png"))); // NOI18N
        jMenuItem38.setText("Pre Corte Cajas");
        jMenuItem38.setVisible(false);
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem38);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rep.png"))); // NOI18N
        if(accesoSistema.licencia.equals("DEMO")){
            jMenu6.setVisible(false);
        }
        jMenu6.setText("Reportes");
        if(accesoSistema.reportes.equals("0")){
            jMenu6.setVisible(false);
        }
        jMenu6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte.png"))); // NOI18N
        jMenuItem4.setText("Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prod.png"))); // NOI18N
        jMenuItem6.setText("Productos Vendidos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultas.png"))); // NOI18N
        jMenuItem25.setText("Venta a Detalle");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem25);

        jMenuBar1.add(jMenu6);

        jMenu9.setText("Utilerias");
        jMenu9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jMenuItem22.setText("Cambiar de Usuario");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem22);

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono_libro.png"))); // NOI18N
        jMenuItem7.setText("Consultar Costo (F3)");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seg.png"))); // NOI18N
        jMenuItem10.setText("Agenda");
        if(accesoSistema.agenda.equals("0")){
            jMenuItem10.setVisible(false);
        }
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto_bajo.png"))); // NOI18N
        jMenuItem8.setText("Respaldo BD");
        if(accesoSistema.respaldo.equals("0")){
            jMenuItem8.setVisible(false);
        }
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        jMenuItem9.setText("Calculadora");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuItem20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cotizacion.png"))); // NOI18N
        jMenuItem20.setText("Cotizaciones");
        if(accesoSistema.cotizaciones.equals("0")){
            jMenuItem20.setVisible(false);
        }
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consultas.png"))); // NOI18N
        jMenuItem21.setText("Consultar Cotizaciones");
        if(accesoSistema.cotizaciones.equals("0")){
            jMenuItem21.setVisible(false);
        }
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem21);

        jMenuItem29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peluqueria2.png"))); // NOI18N
        jMenuItem29.setText("Estetica Canina");
        if(accesoSistema.menuveterinaria.equals("0")){
            jMenuItem29.setVisible(false);
        }
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem29);

        jMenuItem35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        if(accesoSistema.menuveterinaria.equals("0")){
            jMenuItem35.setVisible(false);
        }
        jMenuItem35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mensaje.png"))); // NOI18N
        jMenuItem35.setText("Notificaciones del dia Veterinaria");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem35);

        jMenuBar1.add(jMenu9);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca.png"))); // NOI18N
        jMenu8.setText("Acerca de..");
        jMenu8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        jMenu7.setText("Salir");
        jMenu7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
         
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        escritorio.removeAll();
        Ventas v1=new Ventas();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Clientes v1=new Clientes();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
         Productos v1=new Productos();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
         Usuarios invent=new Usuarios();        
            invent.setResizable(true);
            invent.setClosable(true);
            escritorio.add(invent);
            invent.show();
            //extiende al maximo la jinternal frame
            try {
                invent.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        escritorio.removeAll();
        Inventario invent=new Inventario();        
            invent.setResizable(true);
            invent.setClosable(true);
            escritorio.add(invent);
            invent.show();
            //extiende al maximo la jinternal frame
            try {
                invent.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
         escritorio.removeAll();
         Configuracion config=new Configuracion();        
            config.setResizable(true);
            config.setClosable(true);
            escritorio.add(config);
            config.show();
            //extiende al maximo la jinternal frame
            try {
                config.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
         ReporteGeneral v1=new ReporteGeneral();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Productos_mas_Vendidos v1=new Productos_mas_Vendidos();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        Activador acercade=new Activador();
        acercade.setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try        
        {
            Runtime rt = Runtime.getRuntime();           
            Process p = rt.exec("calc");            
            p.waitFor();        
        }        
        catch ( IOException ioe )       
        {            
            ioe.printStackTrace();
        }         
        catch ( InterruptedException ie )
        {            
            ie.printStackTrace();     
        }
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        
         Frame f = JOptionPane.getFrameForComponent(this);
        ConsultarPrecio consultaprecio=new ConsultarPrecio(f,true);
        consultaprecio.show();
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        RespaldoBD RES=new RespaldoBD(f,true);
        RES.show();
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        Calendario calen=new Calendario(f,true);
        calen.show(); 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Cierre_caja v1=new Cierre_caja();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        PreCierre_caja v1=new PreCierre_caja();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        
        Catfideliza fidelizacion=new Catfideliza();
        fidelizacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Categorias v1=new Categorias();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Proveedores v1=new Proveedores();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        ReporteCompras v1=new ReporteCompras();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        CatProveedores v1=new CatProveedores();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
       
            
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        ReporteDetallado v1=new ReporteDetallado();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 2) {             
             Frame f = JOptionPane.getFrameForComponent(this);
             CambiarContra dialog = new CambiarContra(f,true);
             dialog.show();
         }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        Cotizacion v1=new Cotizacion();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
         Frame f = JOptionPane.getFrameForComponent(this);
        ConsultarCotizaciones consultar=new ConsultarCotizaciones(f,true);
        consultar.show();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        CambiarUsuario cambio=new CambiarUsuario(f,true);
        cambio.show();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         Traspasos invent=new Traspasos();        
            invent.setResizable(true);
            invent.setClosable(true);
            escritorio.add(invent);
            invent.show();
            //extiende al maximo la jinternal frame
            try {
                invent.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
         RecepciondeProductos recepcion=new RecepciondeProductos();        
            recepcion.setResizable(true);
            recepcion.setClosable(true);
            escritorio.add(recepcion);
            recepcion.show();
            //extiende al maximo la jinternal frame
            try {
                recepcion.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
        ProductosVendidosCosto v1=new ProductosVendidosCosto();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
         FacturarTicket facturarticket=new FacturarTicket();
         facturarticket.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        FacturarTicketMasivo masivo=new FacturarTicketMasivo();
        masivo.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        FacturasGeneradas facturasemitidas=new FacturasGeneradas();
        facturasemitidas.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        EsteticaRep v1=new EsteticaRep();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
          NotaCredito v1=new NotaCredito();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
          Frame f = JOptionPane.getFrameForComponent(this);
        ConsultarNotasCredito consultanota=new ConsultarNotasCredito(f,true);
        consultanota.show();
        
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         Comandera rest=new Comandera();        
            rest.setResizable(true);
            rest.setClosable(true);
            escritorio.add(rest);
            rest.show();
            //extiende al maximo la jinternal frame
            try {
                rest.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        RestMesas v1=new RestMesas();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        // TODO add your handling code here:
        ServicioTec ser=new ServicioTec();
        ser.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
        Frame f = JOptionPane.getFrameForComponent(this);
        NotificacionesDiarias notificaciones=new NotificacionesDiarias(f,true);
        notificaciones.show();
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
         Pos_Ventas invent=new Pos_Ventas();        
            invent.setResizable(true);
            invent.setClosable(true);
            escritorio.add(invent);
            invent.show();
            //extiende al maximo la jinternal frame
            try {
                invent.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
        LectorXML xml=new LectorXML();
        xml.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
         CorteCajas v1=new CorteCajas();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        // TODO add your handling code here:
        Inicial ini=new Inicial();
        ini.setVisible(true);
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        // TODO add your handling code here:
        System.out.println("lote farmacias");
         escritorio.removeAll();
         CatalogoLotes v1=new CatalogoLotes();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    /**Este metodo se ejecuta cuando se suelta una tecla*/

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private static javax.swing.JMenu jMenu1;
    private static javax.swing.JMenu jMenu10;
    private static javax.swing.JMenu jMenu11;
    private static javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private static javax.swing.JMenu jMenu2;
    private static javax.swing.JMenu jMenu3;
    private static javax.swing.JMenu jMenu4;
    private static javax.swing.JMenu jMenu5;
    private static javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    public static javax.swing.JMenuBar jMenuBar1;
    private static javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private static javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private static javax.swing.JMenuItem jMenuItem2;
    private static javax.swing.JMenuItem jMenuItem20;
    private static javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private static javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private static javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jllogo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        System.out.println("Soltó la tecla:  "+e.getKeyText(e.getKeyCode()));   
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println("Soltó la tecla:  "+e.getKeyText(e.getKeyCode()));   
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
         System.out.println("Soltó la tecla:  "+e.getKeyText(e.getKeyCode()));   
        if (e.VK_F1==e.getKeyCode())
        {
            int respuesta = JOptionPane.showConfirmDialog(this,
             "Esta seguro que desea salir?", "Confirmación",
             JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_NO_OPTION)
            {
              System.exit(0);
            }
       }
        
    }

public static void validamenu(){
   
    if(accesoSistema.ventas.equals("1")){
        jMenu1.setVisible(true);
        escritorio.removeAll();
            Ventas v1=new Ventas();                
            v1.setResizable(true);
            v1.setClosable(true);
            escritorio.add(v1);
            v1.show();
            //extiende al maximo la jinternal frame
            try {
                v1.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }else{
        escritorio.removeAll();
        jMenu1.setVisible(false);
    }
    
    if(accesoSistema.catcliente.equals("1")){//CLIENTES
        jMenuItem1.setVisible(true);
    }else{
        jMenuItem1.setVisible(false);
    }
    if(accesoSistema.catprod.equals("1")){ //CAT PROD
        jMenuItem2.setVisible(true);
    }else{
        jMenuItem2.setVisible(false);
    }
    if(accesoSistema.catusuario.equals("1")){ //CAT USUARIOS
        jMenuItem3.setVisible(true);
    }else{
        jMenuItem3.setVisible(false);
    }
    if(accesoSistema.catcateg.equals("1")){//CAT CATEGORIA
        jMenuItem14.setVisible(true);
    }else{
        jMenuItem14.setVisible(false);
    }
    if(accesoSistema.privilegio.equals("ADMINISTRADOR")){
        jMenu4.setVisible(true);
    }else{
        jMenu4.setVisible(false);
    }
    if(accesoSistema.traspasos.equals("1")){
        jMenu11.setVisible(true);    
    }else{
        jMenu11.setVisible(false);
    }
    if(accesoSistema.proveedores.equals("1")){
        jMenu10.setVisible(true);
    }else{    
        jMenu10.setVisible(false);
    }
    if(accesoSistema.inventarios.equals("1")){
        jMenu3.setVisible(true);
    }else{
        jMenu3.setVisible(false);
    }
    if(accesoSistema.cierrecaja.equals("1")){
        jMenu5.setVisible(true);
    }else{
        jMenu5.setVisible(false);
    }
    if(accesoSistema.reportes.equals("1")){
        jMenu6.setVisible(true);
    }else{
        jMenu6.setVisible(false);
    }
    if(accesoSistema.cotizaciones.equals("1")){
        jMenuItem20.setVisible(true);
        jMenuItem21.setVisible(true);
    }else{
        jMenuItem20.setVisible(false);
        jMenuItem21.setVisible(false);
    }
    if(accesoSistema.respaldo.equals("1")){
        jMenuItem8.setVisible(true);
    }else{
        jMenuItem8.setVisible(false);
    }
    if(accesoSistema.agenda.equals("1")){
        jMenuItem10.setVisible(true);
    }else{    
        jMenuItem10.setVisible(false);
    }
    if(accesoSistema.menufacturacion.equals("1")){
        jMenu12.setVisible(true);
    }else{    
        jMenu12.setVisible(false);
    }
    if(accesoSistema.catprod.equals("1") || accesoSistema.catcateg.equals("1") || accesoSistema.catcliente.equals("1") || accesoSistema.catusuario.equals("1")){
        jMenu2.setVisible(true);
    }else{
        jMenu2.setVisible(false);
    }
}


public void validamulticajas(){                  
        conex con=new conex();   
        ResultSet rsR = null;        
        String myQuery = "select count(id_cierre_caja) as total from to_cierre_caja";
               System.out.println(""+myQuery);
               try {
                   Statement st = con.getConnection().createStatement();
                   rsR = st.executeQuery(myQuery);
                   while(rsR.next()) { 
                       int i=rsR.getInt("total");
                       if(i>1){
                            jMenuItem38.setVisible(true);
                       }
                   }                             
                   rsR.close(); 
                   st.close();
                   con.desconectar();
               } catch (SQLException ex) {                         
                   //JOptionPane.showMessageDialog(null, "Error al obtener la informacion: "+ex, "Error", JOptionPane.ERROR_MESSAGE);
               }     
              
              
    }    
}
